#!/usr/bin/env python3
"""Emit the verbatim text constants for PlayerbotLlmPrompt.h from banklib.

The byte-diff gate requires the shipped renderer to reproduce the
training text EXACTLY. Hand-transcription of ~6 KB of prompt text is a
typo factory, so this script imports the training source of truth
(G:\\NPU LLM\\scripts\\finetune\\banklib.py) and writes the C++ string
constants for the header. Run it once when regenerating
native/patches/playerbots/PlayerbotLlmPrompt.h constants; the generated
block is delimited by markers so it can be re-emitted in place.

Usage: python tools/llm_lab/emit_prompt_constants.py
"""
from __future__ import annotations

import sys
from pathlib import Path

BANKLIB_DIR = r"G:\NPU LLM\scripts\finetune"
sys.path.insert(0, BANKLIB_DIR)
import banklib as B  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "native" / "patches" / "playerbots" / "PlayerbotLlmPrompt.h"
RECALL_HEADER = ROOT / "native" / "patches" / "playerbots" / "PlayerbotLlmRecallCore.h"

# rev-3b beat-cargo frames: C++ array name -> banklib variant kind
FRAME_ARRAYS = [
    ("kDebtCargoFrames", "debt"),
    ("kMemoryCargoFrames", "memory"),
    ("kMemoryAskCargoFrames", "memory_ask"),
    ("kGrudgeCargoFrames", "grudge"),
    ("kNewsCargoFrames", "news"),
    ("kGossipCargoFrames", "gossip"),
    ("kCeremonyUpFrames", "ceremony_up"),
    ("kCeremonyDownFrames", "ceremony_down"),
]


def cpp_str(text: str) -> str:
    """C++11 string literal, split into quoted lines at newline boundaries
    so every line of the multi-line constants stays readable (adjacent
    literals concatenate; every line except the last carries \\n)."""
    lines = text.split("\n")
    out = []
    for i, line in enumerate(lines):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        suffix = "\\n" if i < len(lines) - 1 else ""
        out.append(f'"{escaped}{suffix}"')
    return "\n".join(out)


def emit() -> str:
    parts = []
    parts.append("// ---- verbatim training text (generated by")
    parts.append("// tools/llm_lab/emit_prompt_constants.py from banklib.py;")
    parts.append("// do not hand-edit between the markers) ----")
    parts.append("namespace pocketllm { namespace training {")
    parts.append("")
    parts.append("// prtools3 v3.2 TOOLS_NOTE + the F7 example-block variants")
    for name, text in (("TOOLS_NOTE_A", B.TOOLS_NOTE), ("TOOLS_NOTE_B", B.TOOLS_NOTE_B),
                       ("TOOLS_NOTE_C", B.TOOLS_NOTE_C), ("TOOLS_NOTE_D", B.TOOLS_NOTE_D)):
        parts.append(f"char const* const {name} =")
        parts.append(cpp_str(text) + ";")
        parts.append("")
    parts.append("// rp-web.NO_NARRATE verbatim")
    parts.append("char const* const NO_NARRATE =")
    parts.append(cpp_str(B.NO_NARRATE) + ";")
    parts.append("")
    parts.append("// the four production bibles (rp-web.BIBLE) - merge-time")
    parts.append("// anti-echo corpus; every bot draws one by stable id hash")
    for name in ("Grumph", "Gromnak", "Maera", "Thren"):
        parts.append(f"char const* const BIBLE_{name.upper()} =")
        parts.append(cpp_str(B.PRODUCTION_BIBLES[name]) + ";")
        parts.append("")
    parts.append("// LEDGER_AVOID note verbatim (first 14 entries joined)")
    parts.append("char const* const LEDGER_AVOID_NOTE =")
    parts.append(cpp_str(B.LEDGER_AVOID_NOTE) + ";")
    parts.append("")
    parts.append("} } // namespace pocketllm::training")
    parts.append("// ---- end verbatim training text ----")
    return "\n".join(parts) + "\n"


def emit_recall() -> str:
    """The beat-cargo variant frames (the wording lock) as C++ array
    constants for PlayerbotLlmRecallCore.h. The frames are authored in
    banklib.BEAT_CARGO_VARIANTS and byte-mirrored here; the bridge selects
    one per bot GUID-stably (flavor = botGuid % 3)."""
    laws = B.check_beat_frames()
    assert not laws, f"banklib beat frames violate the law block: {laws}"
    parts = []
    parts.append("// ---- beat-cargo frames (generated by")
    parts.append("// tools/llm_lab/emit_prompt_constants.py from banklib.py")
    parts.append("// BEAT_CARGO_VARIANTS - the S11 rev-3b wording lock; the")
    parts.append("// banks train these exact frames, and the bridge selects")
    parts.append("// one flavor per bot, GUID-stably (flavor = botGuid % 3).")
    parts.append("// Do not hand-edit between the markers. ----")
    for arr, kind in FRAME_ARRAYS:
        parts.append(f"static char const* const {arr}[] = {{")
        for frame in B.BEAT_CARGO_VARIANTS[kind]:
            parts.append("    " + cpp_str(frame) + ",")
        parts.append("};")
        parts.append("")
    parts.append("// the ceremony {T} phrases, indexed by tier 3/4/5")
    parts.append("static char const* const kCeremonyUpPhrases[] = {")
    for tier in (3, 4, 5):
        parts.append(f"    /* tier {tier} */ " + cpp_str(B.CEREMONY_UP_PHRASES[tier]) + ",")
    parts.append("};")
    parts.append("")
    parts.append("// the S11 P50/P51 long-form cue (banklib.LONGFORM_CUE):")
    parts.append("// ONE frozen signal, appended to the beat cargo only when")
    parts.append("// LongFormLicensed(maxNewTokens) clears the long bank.")
    parts.append("static char const* const kLongFormCue =")
    parts.append("    " + cpp_str(B.LONGFORM_CUE) + ";")
    parts.append("// ---- end beat-cargo frames ----")
    return "\n".join(parts) + "\n"


def splice(path: Path, block: str, begin: str, end_marker: str) -> None:
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    if begin not in text:
        # NEVER write the block as the whole file: a first emission without
        # markers once replaced PlayerbotLlmRecallCore.h outright (recovered
        # from the submodule mirror). Markers are added by hand where the
        # block belongs; the emitter only ever renews between them.
        raise SystemExit(
            f"{path.name} carries no '{begin}' marker - add the marker pair "
            "at the intended splice site by hand, then re-run")
    pre = text[: text.index(begin)]
    post = text[text.index(end_marker) + len(end_marker):]
    # idempotence: strip the seam newlines on BOTH sides so re-running
    # the emitter never accumulates blank lines
    text = pre.rstrip("\n") + "\n\n" + block + post.lstrip("\n")
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="regenerate in memory and diff against the files; "
                         "exit 1 on drift (never writes)")
    args = ap.parse_args()

    block = emit().rstrip("\n") + "\n"
    recall_block = emit_recall().rstrip("\n") + "\n"

    if args.check:
        current = HEADER.read_text(encoding="utf-8") if HEADER.is_file() else ""
        rcurrent = (RECALL_HEADER.read_text(encoding="utf-8")
                    if RECALL_HEADER.is_file() else "")
        ok = True
        if block not in current:
            print(f"DRIFT: {HEADER.name} verbatim block does not match banklib")
            ok = False
        if recall_block not in rcurrent:
            print(f"DRIFT: {RECALL_HEADER.name} beat-cargo frames do not "
                  "match banklib - re-run the emitter")
            ok = False
        if ok:
            print("emitted constants are fresh (byte-identical to banklib)")
        return 0 if ok else 1

    splice(HEADER, block,
           "// ---- verbatim training text (generated by",
           "// ---- end verbatim training text ----")
    print(f"wrote {HEADER} ({len(block)} bytes of verbatim constants)")
    # sanity: round-trip one constant through a C++-escaped reparse (the
    # text contains ';' so the block is delimited by the next declaration)
    import re
    start = block.index("char const* const NO_NARRATE =")
    nxt = block.index("char const* const", start + 10)
    lit = block[start: nxt].split("=\n", 1)[1]
    lit = lit[: lit.rindex(";")]
    joined = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', lit))
    decoded = joined.replace("\\n", "\n").replace('\\"', '"').replace("\\\\", "\\")
    assert decoded == B.NO_NARRATE, "round-trip mismatch on NO_NARRATE"
    print("round-trip check OK")

    recall_block = emit_recall().rstrip("\n") + "\n"
    splice(RECALL_HEADER, recall_block,
           "// ---- beat-cargo frames (generated by",
           "// ---- end beat-cargo frames ----")
    print(f"wrote {RECALL_HEADER} ({len(recall_block)} bytes of beat-cargo frames)")
    # sanity: round-trip one frame of every placeholder class
    import re as _re
    for arr, kind in FRAME_ARRAYS:
        seg = recall_block.split(f"static char const* const {arr}[] = {{", 1)[1]
        seg = seg.split("};", 1)[0]
        joined = "".join(_re.findall(r'"((?:[^"\\]|\\.)*)"', seg))
        for frame in B.BEAT_CARGO_VARIANTS[kind]:
            assert frame in joined, f"round-trip mismatch on {kind}"
    print("beat-cargo round-trip check OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
