#!/usr/bin/env python3
"""Emit the verbatim text constants for PlayerbotLlmPrompt.h from banklib.

The A4/A5 byte-diff gate requires the shipped renderer to reproduce the
training text EXACTLY. Hand-transcription of ~6 KB of prompt text is a
typo factory, so this script imports the training source of truth
(G:\\NPU LLM\\scripts\\finetune\\banklib.py) and writes the C++ string
constants for the header. Run it once when regenerating
native/patches/playerbots/PlayerbotLlmPrompt.h constants; the generated
block is delimited by markers so it can be re-emitted in place.

Usage: python tools/llm_lab/emit_prompt_constants.py
"""
from __future__ import annotations

import sys
from pathlib import Path

BANKLIB_DIR = r"G:\NPU LLM\scripts\finetune"
sys.path.insert(0, BANKLIB_DIR)
import banklib as B  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "native" / "patches" / "playerbots" / "PlayerbotLlmPrompt.h"


def cpp_str(text: str) -> str:
    """C++11 string literal, split into quoted lines at newline boundaries
    so every line of the multi-line constants stays reviewable (adjacent
    literals concatenate; every line except the last carries \\n)."""
    lines = text.split("\n")
    out = []
    for i, line in enumerate(lines):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        suffix = "\\n" if i < len(lines) - 1 else ""
        out.append(f'"{escaped}{suffix}"')
    return "\n".join(out)


def emit() -> str:
    parts = []
    parts.append("// ---- verbatim training text (generated by")
    parts.append("// tools/llm_lab/emit_prompt_constants.py from banklib.py;")
    parts.append("// do not hand-edit between the markers) ----")
    parts.append("namespace pocketllm { namespace training {")
    parts.append("")
    parts.append("// prtools3 v3.2 TOOLS_NOTE + the F7 example-block variants")
    for name, text in (("TOOLS_NOTE_A", B.TOOLS_NOTE), ("TOOLS_NOTE_B", B.TOOLS_NOTE_B),
                       ("TOOLS_NOTE_C", B.TOOLS_NOTE_C), ("TOOLS_NOTE_D", B.TOOLS_NOTE_D)):
        parts.append(f"char const* const {name} =")
        parts.append(cpp_str(text) + ";")
        parts.append("")
    parts.append("// rp-web.NO_NARRATE verbatim")
    parts.append("char const* const NO_NARRATE =")
    parts.append(cpp_str(B.NO_NARRATE) + ";")
    parts.append("")
    parts.append("// the four production bibles (rp-web.BIBLE) - merge-time")
    parts.append("// anti-echo corpus; every bot draws one by stable id hash")
    for name in ("Grumph", "Gromnak", "Maera", "Thren"):
        parts.append(f"char const* const BIBLE_{name.upper()} =")
        parts.append(cpp_str(B.PRODUCTION_BIBLES[name]) + ";")
        parts.append("")
    parts.append("// LEDGER_AVOID note verbatim (first 14 entries joined)")
    parts.append("char const* const LEDGER_AVOID_NOTE =")
    parts.append(cpp_str(B.LEDGER_AVOID_NOTE) + ";")
    parts.append("")
    parts.append("} } // namespace pocketllm::training")
    parts.append("// ---- end verbatim training text ----")
    return "\n".join(parts) + "\n"


def main() -> int:
    text = HEADER.read_text(encoding="utf-8") if HEADER.is_file() else ""
    block = emit().rstrip("\n") + "\n"
    begin = "// ---- verbatim training text (generated by"
    if begin in text:
        pre = text[: text.index(begin)]
        end_marker = "// ---- end verbatim training text ----"
        post = text[text.index(end_marker) + len(end_marker):]
        # idempotence: strip the seam newlines on BOTH sides so re-running
        # the emitter never accumulates blank lines
        text = pre.rstrip("\n") + "\n\n" + block + post.lstrip("\n")
    else:
        text = block
    HEADER.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {HEADER} ({len(block)} bytes of verbatim constants)")
    # sanity: round-trip one constant through a C++-escaped reparse (the
    # text contains ';' so the block is delimited by the next declaration)
    import re
    start = block.index("char const* const NO_NARRATE =")
    nxt = block.index("char const* const", start + 10)
    lit = block[start: nxt].split("=\n", 1)[1]
    lit = lit[: lit.rindex(";")]
    joined = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', lit))
    decoded = joined.replace("\\n", "\n").replace('\\"', '"').replace("\\\\", "\\")
    assert decoded == B.NO_NARRATE, "round-trip mismatch on NO_NARRATE"
    print("round-trip check OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
