#!/usr/bin/env python3
"""Extract the FROZEN bridge wording into the bank-authoring tree.

The guard bank trains the entity-guard directive and the murmur bank
trains the device-path chatter wording - the wording lock demands
the banks compose rows with the EXACT bytes the bridge injects. Those
strings are authored and byte-pinned on the C++ side
(PlayerbotLlmTruthCore.h GuardDirective + PlayerbotLlmChatterCore.h
Murmur*/Party*/Global*/Composer*), so this extractor COMPILES a tiny
host program that includes both cores, renders every frozen string with
sentinel parameters, and writes them as python constants into
bridge_wording.py in the bank-authoring tree, between markers.

No hand transcription anywhere: the C++ itself renders the strings, the
sentinels convert to format placeholders, and --check regenerates to a
temp file and diffs against the committed module so drift fails loud.

Usage:
  python tools/llm_lab/extract_bridge_wording.py          # write/refresh
  python tools/llm_lab/extract_bridge_wording.py --check  # fresh? exit 1 if not
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PATCHES = ROOT / "native" / "patches" / "playerbots"


def _banklib_dir() -> Path:
    """The bank-authoring tree is external to the repo (it holds the
    training banks); point LLM_LAB_BANKLIB_DIR at a local checkout. There
    is no default: an unset variable exits with a message naming it."""
    d = os.environ.get("LLM_LAB_BANKLIB_DIR")
    if not d:
        sys.stderr.write("LLM_LAB_BANKLIB_DIR is not set - point it at "
                         "the bank-authoring tree checkout\n")
        raise SystemExit(2)
    return Path(d)


OUT = _banklib_dir() / "bridge_wording.py"
BEGIN = "# ---- bridge wording (generated by extract_bridge_wording.py"
END = "# ---- end bridge wording ----"

HOST_SRC = r"""
#include <cstdio>
#include <string>
#include <vector>
#include "PlayerbotLlmChatterCore.h"
#include "PlayerbotLlmTruthCore.h"

// tab- and newline-safe emit: values are escaped so one printf line
// carries the whole string
std::string esc(std::string const& s)
{
    std::string out;
    for (char c : s)
    {
        if (c == '\n') out += "\\n";
        else if (c == '\t') out += "\\t";
        else if (c == '\r') out += "\\r";
        else if (c == '\f') out += "\\f";
        else if (c == '\v') out += "\\v";
        else if (c == '\0') out += "\\0";
        else if (c == '\\') out += "\\\\";
        else out += c;
    }
    return out;
}

// renders every FROZEN bridge string with sentinel parameters so the
// extractor can convert them to python format templates byte-exactly
int main()
{
    std::printf("GUARD_DIRECTIVE\t%s\n", esc(pocketllm::GuardDirective("@@X@@", "@@cls@@")).c_str());
    std::printf("MURMUR_SYSTEM_MESSAGE\t%s\n", esc(pocketllm::MurmurSystemMessage(
        "@@name@@", "@@race@@", "@@cls@@", "@@zone@@", "@@demeanor@@",
        "@@quirk@@", "@@gripe@@")).c_str());
    std::printf("MURMUR_NOTE\t%s\n", esc(pocketllm::MurmurNote("@@listener@@", "@@event@@")).c_str());
    std::printf("PARTY_NOTE\t%s\n", esc(pocketllm::PartyNote("@@player@@", "@@event@@")).c_str());
    std::printf("GLOBAL_NOTE\t%s\n", esc(pocketllm::GlobalNote("@@event@@")).c_str());
    std::printf("COMPOSER_SYSTEM_PROMPT\t%s\n", esc(pocketllm::ComposerSystemPrompt()).c_str());
    std::printf("COMPOSER_USER_PROMPT\t%s\n", esc(pocketllm::ComposerUserPrompt(
        std::vector<std::string>(1, "@@persona@@"),
        std::vector<std::string>(1, "@@event@@")).c_str()).c_str());
    return 0;
}
"""

SENTINELS = {
    "@@X@@": "{X}",
    "@@cls@@": "{cls}",
    "@@name@@": "{name}",
    "@@race@@": "{race}",
    "@@zone@@": "{zone}",
    "@@demeanor@@": "{demeanor}",
    "@@quirk@@": "{quirk}",
    "@@gripe@@": "{gripe}",
    "@@listener@@": "{listener}",
    "@@player@@": "{player}",
    "@@event@@": "{event}",
    "@@persona@@": "{persona}",
}

HEADER = '''"""FROZEN bridge wording for bank authoring (P45 guard + P52 murmur).

Generated from the C++ source of truth by
tools/llm_lab/extract_bridge_wording.py - the strings between the
markers are byte-exact renders of PlayerbotLlmTruthCore.h's A10
directive and PlayerbotLlmChatterCore.h's device-path chatter wording.
The banks compose training rows from THESE templates (the wording lock:
train what the bridge injects). The composer_user_prompt helper below
the markers is verified byte-exact against the C++ render on every
extraction run. Never hand-edit; re-run the extractor instead.
"""

'''

FOOTER = '''

def guard_directive(entity, cls):
    """The A10 note body (person/place/thing) - compose(extra=...) adds
    the [BRIDGE AI] furniture and the reply-only footer."""
    return GUARD_DIRECTIVE.replace("{X}", entity).replace("{cls}", cls)


def murmur_system(**kw):
    return MURMUR_SYSTEM_MESSAGE.format(**kw)


def murmur_note(listener, event):
    return MURMUR_NOTE.replace("{listener}", listener).replace("{event}", event)


def party_note(player, event):
    return PARTY_NOTE.replace("{player}", player).replace("{event}", event)


def global_note(event):
    return GLOBAL_NOTE.replace("{event}", event)


def composer_user_prompt(persona_lines, event_rows):
    """Structural render (list joining) - verified byte-exact against the
    C++ ComposerUserPrompt on every extraction run."""
    return ("Characters:\\n"
            + "".join("- " + p + "\\n" for p in persona_lines)
            + "News to talk about:\\n"
            + "".join("- " + e + "\\n" for e in event_rows)
            + "Write the exchange.")
'''


def render_constants() -> dict:
    gxx = "g++"
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        src = tdp / "host.cpp"
        src.write_text(HOST_SRC, encoding="utf-8", newline="\n")
        exe = tdp / "host.exe"
        build = subprocess.run(
            [gxx, "-std=c++11", "-O0", "-I", str(PATCHES), "-o", str(exe), str(src)],
            capture_output=True, text=True)
        if build.returncode != 0:
            sys.exit(f"host render failed to compile:\n{build.stderr[:2000]}")
        run = subprocess.run([str(exe)], capture_output=True, text=True)
        if run.returncode != 0:
            sys.exit("host render failed to run")
    out = {}
    # split strictly on \n (splitlines() would also break on \r/\f/\v and
    # corrupt the record framing); the sentinel walk decodes backslash
    # escapes with the doubled backslash held aside
    for line in run.stdout.split("\n"):
        if not line:
            continue
        key, _, value = line.partition("\t")
        out[key] = (value.replace("\\\\", "\x00")
                    .replace("\\n", "\n").replace("\\t", "\t")
                    .replace("\\r", "\r").replace("\\f", "\f")
                    .replace("\\v", "\v")
                    .replace("\x00", "\\"))
        # the framing guarantee: after decode, no control byte may remain
        # except the two legal whitespace forms (a NUL would already have
        # truncated the printf %s leg on the C++ side - this catches any
        # other protocol break)
        assert not any(ord(c) < 0x20 and c not in "\n\t"
                       for c in out[key]), \
            f"{key}: control byte survived the round-trip"
    expected = {"GUARD_DIRECTIVE", "MURMUR_SYSTEM_MESSAGE", "MURMUR_NOTE",
                "PARTY_NOTE", "GLOBAL_NOTE", "COMPOSER_SYSTEM_PROMPT",
                "COMPOSER_USER_PROMPT"}
    missing = expected - set(out)
    assert not missing, f"host render missed constants: {missing}"
    return out


def compose_module(constants: dict, composer_check: bool = True) -> str:
    lines = [HEADER.rstrip("\n"), "", BEGIN]
    for key in ("GUARD_DIRECTIVE", "MURMUR_SYSTEM_MESSAGE", "MURMUR_NOTE",
                "PARTY_NOTE", "GLOBAL_NOTE", "COMPOSER_SYSTEM_PROMPT"):
        text = constants[key]
        for sent, ph in SENTINELS.items():
            text = text.replace(sent, ph)
        # braces break .format(): BOTH stray { and } must be absent once
        # the placeholders are stripped (a lone } fails format just as
        # hard as a lone {)
        stripped = text
        for ph in set(SENTINELS.values()):
            stripped = stripped.replace(ph, "")
        assert "{" not in stripped and "}" not in stripped, \
            f"{key} grew a literal brace"
        # newline/tab-safe python literal (the C++ esc protocol carries
        # real newlines for multi-line renders)
        lit = (text.replace("\\", "\\\\").replace('"', '\\"')
               .replace("\n", "\\n").replace("\t", "\\t"))
        lines.append(f'{key} = "{lit}"')
    # the composer user prompt keeps its list sentinels as documentation
    # of shape; the helper renders the real thing
    cup = constants["COMPOSER_USER_PROMPT"] \
        .replace("\\", "\\\\").replace('"', '\\"') \
        .replace("\n", "\\n").replace("\t", "\\t")
    lines.append(f'# rendered shape (single-element lists): "{cup}"')
    lines.append(END)
    lines.append(FOOTER.rstrip("\n"))
    lines.append("")
    module = "\n".join(lines)

    if composer_check:
        # verify the static helper renders byte-exactly vs the C++
        import importlib.util
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "bw.py"
            p.write_text(module, encoding="utf-8", newline="\n")
            spec = importlib.util.spec_from_file_location("bw", p)
            bw = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(bw)
            rendered = bw.composer_user_prompt(["@@persona@@"], ["@@event@@"])
            assert rendered == constants["COMPOSER_USER_PROMPT"], \
                "composer_user_prompt helper drifted from the C++ render"
    return module


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="regenerate to a temp file and diff; exit 1 on drift")
    args = ap.parse_args()

    constants = render_constants()
    module = compose_module(constants)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != module:
            print(f"DRIFT: {OUT} does not match the C++ render - re-run "
                  "the extractor without --check")
            return 1
        print(f"{OUT.name} is fresh (byte-identical to the C++ render)")
        return 0

    OUT.write_text(module, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(constants)} frozen constants)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
