// Generated by tools/generate_community_vulkan_drivers.py.
// Edit schemas/community-vulkan-drivers.json, then regenerate; do not edit this file.
package com.pocketrealm.client

internal object GeneratedCommunityVulkanDrivers {
    const val SCHEMA: Int = 1
    const val POLICY: String = "pinned-digest-download-only"
    const val SOURCE_MANIFEST_SHA256: String = "112bc2206a01893c026e84e6c816d5663e225638f9179a1ea31a2e72bdab7f46"

    val drivers: List<CommunityVulkanDriver> = listOf(
        CommunityVulkanDriver(
            id = "community-turnip-26.0.0-r8",
            label = "Mesa Turnip 26.0.0 R8 (K11MCH1)",
            version = "26.0.0",
            repo = "K11MCH1/AdrenoToolsDrivers",
            release = "v26.0.0-rc08",
            url = "https://github.com/K11MCH1/AdrenoToolsDrivers/releases/download/v26.0.0-rc08/Turnip_v26.0.0_R8.zip",
            size = 3478359L,
            sha256 = "e634db0f929e2205e95511c769071817d0390180ec72c8e690bc76375e813715",
            librarySha256 = "fdd378520022f88b0363dd1f77f6989332730271712621523075fe4eb4de2a09",
            format = "adrenotools-zip",
            license = "MIT",
            upstream = "mesa 26.0.0-devel freedreno/Turnip",
            summary = "Mesa Turnip built from 26.0.0-devel by the K11MCH1 AdrenoToolsDrivers project; reports Vulkan 1.4.335.",
            note = "Community build, not qualified by Pocket Realm. Ships unsupported-GPU hacks per its release notes; the crash guard applies.",
        ),
        CommunityVulkanDriver(
            id = "community-turnip-25.1.0-r2",
            label = "Mesa Turnip 25.1.0 R2 (K11MCH1)",
            version = "25.1.0",
            repo = "K11MCH1/WinlatorTurnipDrivers",
            release = "winlator_v25.1_r2",
            url = "https://github.com/K11MCH1/WinlatorTurnipDrivers/releases/download/winlator_v25.1_r2/libvulkan_freedreno.so",
            size = 10593080L,
            sha256 = "fe222ea204d5ac312eae2955da4a7b78c087009f28403edceec73e4ed1ae64da",
            librarySha256 = "fe222ea204d5ac312eae2955da4a7b78c087009f28403edceec73e4ed1ae64da",
            format = "bare-so",
            license = "MIT",
            upstream = "mesa 25.1.0 freedreno/Turnip",
            summary = "Bare libvulkan_freedreno.so from the K11MCH1 WinlatorTurnipDrivers project; the conservative fallback that predates the AdrenoTools pack format.",
            note = "Community build, not qualified by Pocket Realm. Same import validation and crash guard as any imported driver.",
        ),
    )
}
