// Generated by tools/generate_vulkan_driver_catalog.py.
// Edit schemas/vulkan-driver-catalog.json, then regenerate; do not edit this file.
package com.pocketrealm.client

internal object GeneratedVulkanDriverCatalog {
    const val SCHEMA: Int = 2
    const val DEFAULT_ID: String = "turnip-26.1.0"
    const val SELECTION_POLICY: String = "exact-request-fail-closed"
    const val SOURCE_CATALOG_SHA256: String = "54c34412b9ff59eda88da5d48c9ae1a5b81e07bf15def15a97892b0602f7ed5d"

    val packages: List<VulkanDriverPackage> = listOf(
        VulkanDriverPackage(
            id = "system-vulkan-vortek-2.1",
            label = "System Vulkan driver",
            version = "2.1",
            kind = VulkanDriverKind.SYSTEM,
            summary = "Uses the GPU driver supplied by this Android device through Winlator's Vortek bridge.",
            qualification = "Experimental developer-qualification path; not enabled for normal production launches.",
            libraryAsset = "arm-translated/vulkan-drivers/system-vulkan-vortek-2.1/libvulkan_vortek.so",
            libraryName = "libvulkan_vortek.so",
            librarySha256 = "10208431d516184e0e92ac1612a04c25a2e6a8925e89f3ef4829ee35eb1164d9",
            icdAsset = "arm-translated/vulkan-drivers/system-vulkan-vortek-2.1/vortek_icd.aarch64.json",
            icdFileName = "vortek_icd.aarch64.json",
            icdSha256 = "9e80133ca51ef57dac0cdc29ff8614d1fdffc5335fcf4e8ce38066da43f3c262",
        ),
        VulkanDriverPackage(
            id = "turnip-26.1.0",
            label = "Turnip 26.1.0",
            version = "26.1.0",
            kind = VulkanDriverKind.TURNIP,
            summary = "Uses the packaged Mesa Turnip driver instead of Android's system driver.",
            qualification = "Built-in production default qualified for the RP6 / Adreno 740 lane.",
            libraryAsset = "arm-translated/vulkan-drivers/turnip-26.1.0/libvulkan_freedreno.so",
            libraryName = "libvulkan_freedreno.so",
            librarySha256 = "f4d09b00d5d7e463f1af76a9974bdd4f2d8298951de9ae2bfc7678a3631e7ab0",
            icdAsset = "arm-translated/vulkan-drivers/turnip-26.1.0/freedreno_icd.aarch64.json",
            icdFileName = "freedreno_icd.aarch64.json",
            icdSha256 = "8ab797c2c31441271acee4b2423106683eb9e500de6e168ceb035f02c30aeb92",
        ),
    )
}
