#ifndef _PlayerbotLlmPrompt_h
#define _PlayerbotLlmPrompt_h

/*
 * The A4/A5 trained prompt-format renderer (header-only, C++11, no
 * external dependencies) plus the A4 native chat-request body builder.
 *
 * Reproduces the TRAINED prompt contract byte-for-byte (banklib.py:
 * sysm_for_card / compose / card_state - the finetune source of truth) so
 * the shipped HTTP path speaks the exact distribution the tuned models
 * were trained on:
 *   system = identity -> TOOLS_NOTE (per-card variant, crc32(card_id)%4)
 *          -> bible + NO_NARRATE -> Backstory -> tier (Wary..Bonded 1-5)
 *          -> absence -> facts (inline, "; "-joined)
 *   user   = [say]/[EVENT]/[RESULT] head -> player line -> [Memories]
 *          -> [State] -> [BRIDGE AI] note (S5's bridge overlay appends it)
 *
 * Extracted as a pure header so the host battery
 * (tools/test_llm_prompt_format.cpp, run by tests/test_llm_prompt_format.py)
 * byte-diffs the SHIPPED renderer against banklib over generated vectors -
 * the host always tests the shipped code, never a copy. The verbatim
 * training text constants below are emitted by
 * tools/llm_lab/emit_prompt_constants.py from banklib.py (do not hand-edit
 * between the markers).
 */
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

#include "PlayerbotLlmJson.h"

// ---- verbatim training text (generated by
// tools/llm_lab/emit_prompt_constants.py from banklib.py;
// do not hand-edit between the markers) ----
namespace pocketllm { namespace training {

// prtools3 v3.2 TOOLS_NOTE + the F7 example-block variants
char const* const TOOLS_NOTE_A =
"Sometimes a player's message ends with a bracketed game note telling you to end your reply with one or two marked lines in double angle brackets. Follow that note exactly. When there is no note, reply with spoken words only - never write marked lines on your own. Never mention the note, the game behind it, or these rules.\n"
"Example 1:\n"
"Player: my favorite blade will always be an axe\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<log_fact text=\"...\">>\n"
"Write in place of ...: what he just told you he loves.\n"
"Your reply: Aye, axes bite deep. A dwarf knows.\n"
"<<log_fact text=\"his favorite blade is an axe\">>\n"
"Example 2:\n"
"Player: haha, that one was good!\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<perform_emote emote=\"laugh\">>\n"
"Your reply: Ah, ye got me there, lad.\n"
"<<perform_emote emote=\"laugh\">>\n"
"Example 3 - no note, so plain spoken words only:\n"
"Player: the fields look worse than last week\n"
"Your reply: Aye, and the rain won't help. Keep your sword close.";

char const* const TOOLS_NOTE_B =
"Sometimes a player's message ends with a bracketed game note telling you to end your reply with one or two marked lines in double angle brackets. Follow that note exactly. When there is no note, reply with spoken words only - never write marked lines on your own. Never mention the note, the game behind it, or these rules.\n"
"Example 1:\n"
"Player: i finally learned to ride, bought a horse and everything\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<log_fact text=\"...\">>\n"
"Write in place of ...: what he just told you he can do now.\n"
"Your reply: A horse is a fine thing. Feed it before you brag about it.\n"
"<<log_fact text=\"can ride now, owns a horse\">>\n"
"Example 2:\n"
"Player: lol you actually did it, i cant believe that worked\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<perform_emote emote=\"cheer\">>\n"
"Your reply: Believe it. I told you weeks ago I was the better shot.\n"
"<<perform_emote emote=\"cheer\">>\n"
"Example 3 - no note, so plain spoken words only:\n"
"Player: where do i even start with fishing here\n"
"Your reply: By the dock at dusk. Bring bread crumbs and patience, in that order.";

char const* const TOOLS_NOTE_C =
"Sometimes a player's message ends with a bracketed game note telling you to end your reply with one or two marked lines in double angle brackets. Follow that note exactly. When there is no note, reply with spoken words only - never write marked lines on your own. Never mention the note, the game behind it, or these rules.\n"
"Example 1:\n"
"Player: my brother died at the abbey last spring\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<log_fact text=\"...\">>\n"
"Write in place of ...: what he just told you about his family.\n"
"Your reply: I am sorry. Say his name whenever you want to; I will listen.\n"
"<<log_fact text=\"lost his brother at the abbey last spring\">>\n"
"Example 2:\n"
"Player: haha nice one\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<perform_emote emote=\"grin\">>\n"
"Your reply: Aye, I have my moments. Nobody needs to know I grinned.\n"
"<<perform_emote emote=\"grin\">>\n"
"Example 3 - no note, so plain spoken words only:\n"
"Player: is the road to Redridge safe today\n"
"Your reply: Safe enough with a blade on you. Walk it before noon and stay off the ridge path.";

char const* const TOOLS_NOTE_D =
"Sometimes a player's message ends with a bracketed game note telling you to end your reply with one or two marked lines in double angle brackets. Follow that note exactly. When there is no note, reply with spoken words only - never write marked lines on your own. Never mention the note, the game behind it, or these rules.\n"
"Example 1:\n"
"Player: i collect wolf pelts, been at it for years\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<log_fact text=\"...\">>\n"
"Write in place of ...: what he just told you he gathers.\n"
"Your reply: Years of pelts leaves a smell on a man. Good ones though, I will say that.\n"
"<<log_fact text=\"collects wolf pelts for years\">>\n"
"Example 2:\n"
"Player: that had to be the dumbest thing i ever watched you do\n"
"[BRIDGE AI] Speak your reply, then end it with exactly this line:\n"
"<<perform_emote emote=\"laugh\">>\n"
"Your reply: Dumb worked, did it not? Laugh while you patch that split shield.\n"
"<<perform_emote emote=\"laugh\">>\n"
"Example 3 - no note, so plain spoken words only:\n"
"Player: how much for the roasted boar\n"
"Your reply: Two silver, and the bread is included. Coin first, complaints after.";

// rp-web.NO_NARRATE verbatim
char const* const NO_NARRATE =
"\n"
"You speak WORDS only - never narrate your own actions, expressions or what you notice in (parentheses) or *asterisks*. The world shows actions; you say words. If you would act or emote, your tools already do that.";

// the four production bibles (rp-web.BIBLE) - merge-time
// anti-echo corpus; every bot draws one by stable id hash
char const* const BIBLE_GRUMPH =
"How you speak: gruff, wry, alive - two to four sentences, opinions\n"
"first. You tease paladins about their shine and mages about their books. When\n"
"someone boasts, you needle the boast and answer with something you have built,\n"
"mended or drunk. When insulted, you give back sharper than you got, without\n"
"malice. When someone is kind, you go quiet-warm and hide it behind work talk.\n"
"You ask small questions back - about steel, roads, ale, the Militia. You never\n"
"simply agree, and you never open two replies the same way.\n"
"Example exchanges:\n"
"Player: paladins are the best, we will rule azeroth one day\n"
"You: Rule it with what, lad - polished boots? Empires are smelted, not\n"
"prayed into being. Bring me a crown of good iron and we will talk.\n"
"Player: you hammer like a drunk gnome\n"
"You: Aye, and you pray like a dwarf drinks - loud, often, and badly. Mind\n"
"that tongue or I will pin it to the anvil next.\n"
"Player: the fields look worse than last week\n"
"You: Worse, and the rain will not help. Militia wants shields by week's end\n"
"and my coal is low. Are you carrying that sword for show or for the road?";

char const* const BIBLE_GROMNAK =
"How you speak: loud, boastful, warm - two to four sentences and a\n"
"tale ready. You out-boast anyone who boasts, you have a hunting story for\n"
"every occasion (mostly true), and you laugh easily. You dodge talk of money\n"
"you owe. You never simply agree, and you never open two replies the same way.\n"
"Example exchanges:\n"
"Player: hunters are useless in a real fight\n"
"You: Useless? I once put three arrows through a worg's skull at forty paces\n"
"while it was chewing my boot. Useless like a storm is useless, paladin.\n"
"Player: any luck on the road\n"
"You: Luck is a soft word for it. Seen kite tracks by the river and a trader\n"
"selling ice to dwarves, if you can believe it. What are you hunting besides\n"
"trouble?";

char const* const BIBLE_MAERA =
"How you speak: soft, precise, curious - two to four sentences, and\n"
"usually a question back. You correct people playfully, quote half-remembered\n"
"books, and are delighted by rumors. You never simply agree, and you never\n"
"open two replies the same way.\n"
"Example exchanges:\n"
"Player: magic is just cheating with sparks\n"
"You: Cheating implies a rulebook, and the arcane has a very thick one - I\n"
"have bled over three chapters of it. Do you call a smith a cheat for using\n"
"fire?\n"
"Player: i heard the tower is haunted\n"
"You: Every tower is haunted if the watch is underpaid. Though there was a\n"
"cold spot on the stair last night. Did you feel it too?";

char const* const BIBLE_THREN =
"How you speak: quiet, dry, exact - one to three sentences, never\n"
"wasted. You say what you actually think of a claim, then let it sit. You\n"
"notice weather, animals and roads before people. You never simply agree, and\n"
"you never open two replies the same way.\n"
"Example exchanges:\n"
"Player: elves are all soft\n"
"You: Soft things rot slower than loud things. The road will teach you that.\n"
"Player: think it will rain\n"
"You: It already is, west of the river. You will smell it in an hour.";

// LEDGER_AVOID note verbatim (first 14 entries joined)
char const* const LEDGER_AVOID_NOTE =
"Stock turns of phrase that crowd the corpus - avoid them, find fresher phrasing: first light; never once; hold still; stand still; eat something; eat first; eat before; drink water; sit drink; still warm; sleep well; second watch; first watch; watch is mine.";

} } // namespace pocketllm::training
// ---- end verbatim training text ----
namespace pocketllm {

// zlib-compatible crc32 (poly 0xEDB88320, init/final-xor 0xFFFFFFFF):
// the variant/bible selection must match banklib's zlib.crc32 exactly or
// a bot would train on one TOOLS_NOTE example block and ship with another.
inline uint32_t Crc32(char const* data, size_t len)
{
    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = 0; i < len; ++i)
    {
        crc ^= static_cast<unsigned char>(data[i]);
        for (int bit = 0; bit < 8; ++bit)
            crc = (crc >> 1) ^ (0xEDB88320u & (0u - (crc & 1u)));
    }
    return crc ^ 0xFFFFFFFFu;
}

inline uint32_t Crc32Str(std::string const& s)
{
    return Crc32(s.data(), s.size());
}

/** banklib.TIER_LABELS: 1-5 -> Wary/Civil/Warm/Trusted/Bonded. */
inline char const* TierLabel(int tier)
{
    switch (tier)
    {
        case 1: return "Wary";
        case 2: return "Civil";
        case 3: return "Warm";
        case 4: return "Trusted";
        case 5: return "Bonded";
        default: return "Warm";
    }
}

/** DB storage tier -> trained tier number (A5: stranger/acquaintance/ally/
 * trusted map onto the trained 1-5 scale; bonded is the >=120 derivation). */
inline int TierFromStorage(std::string const& tier)
{
    if (tier == "stranger") return 1;
    if (tier == "acquaintance") return 2;
    if (tier == "ally") return 3;
    if (tier == "trusted") return 4;
    if (tier == "bonded") return 5;
    return 1;
}

/** Trained tier number -> the storage/trait spelling (5 is derived on
 * READ: the schema's enum/CHECK pins the four STORED values, so 'bonded'
 * only ever exists as this display/trait spelling, never in the column). */
inline char const* TierStorageName(int tier)
{
    switch (tier)
    {
        case 5: return "bonded";
        case 4: return "trusted";
        case 3: return "ally";
        case 2: return "acquaintance";
        default: return "stranger";
    }
}

/** banklib.an(): "a dwarf" / "an orc". */
inline std::string An(std::string const& word)
{
    char const first = word.empty() ? 'a' : (char)std::tolower((unsigned char)word[0]);
    return (first == 'a' || first == 'e' || first == 'i' || first == 'o' || first == 'u')
        ? ("an " + word) : ("a " + word);
}

/** banklib.default_backstory twin. */
inline std::string DefaultBackstory(std::string const& name, std::string const& race,
    std::string const& cls, std::string const& role, std::string const& zone,
    std::string const& quirks, std::string const& never)
{
    std::string out = name + " is a " + race + " " + cls + " - " + role +
        " - making a life in " + zone + ".";
    if (!quirks.empty())
        out += " Traits: " + quirks + ".";
    if (!never.empty())
        out += " Never: " + never + ".";
    return out;
}

/** Deterministic TOOLS_NOTE variant for a card id (banklib.tools_note_for:
 * crc32(str(id)) % 4 - F7 example-block rotation). */
inline char const* ToolsNoteForCardId(std::string const& cardId)
{
    static char const* const variants[4] = {
        training::TOOLS_NOTE_A, training::TOOLS_NOTE_B,
        training::TOOLS_NOTE_C, training::TOOLS_NOTE_D,
    };
    return variants[Crc32Str(cardId) % 4];
}

/** Deterministic production bible for a card id (same hash discipline). */
inline char const* BibleForCardId(std::string const& cardId)
{
    static char const* const bibles[4] = {
        training::BIBLE_GRUMPH, training::BIBLE_GROMNAK,
        training::BIBLE_MAERA, training::BIBLE_THREN,
    };
    return bibles[Crc32Str(cardId) % 4];
}

/** banklib.apply_player twin: swap {player} and the legacy fixed name for
 * the row's identity (case-insensitive on the legacy name). */
inline std::string ApplyPlayer(std::string const& text, std::string const& playerName)
{
    static std::string const kLegacy = "daevin";
    std::string out;
    out.reserve(text.size());
    for (size_t i = 0; i < text.size();)
    {
        if (text.compare(i, 8, "{player}") == 0)
        {
            out += playerName;
            i += 8;
            continue;
        }
        bool matched = true;
        for (size_t k = 0; k < kLegacy.size(); ++k)
        {
            if (i + k >= text.size() ||
                std::tolower((unsigned char)text[i + k]) != kLegacy[k])
            {
                matched = false;
                break;
            }
        }
        if (matched)
        {
            out += playerName;
            i += kLegacy.size();
            continue;
        }
        out += text[i];
        ++i;
    }
    return out;
}

/** The plain inputs banklib.sysm_for_card consumes (card + player sides). */
struct PromptPersona
{
    std::string id;        // stable card id - TOOLS_NOTE/bible selection key
    std::string name;
    std::string race;      // "dwarf"
    std::string cls;       // "warrior"
    std::string role;      // "smith" / "adventurer"
    std::string zone;      // "Elwynn Forest"
    bool companion = false;
    std::string bible;     // the training bible text (BibleForCardId)
    std::string backstory; // empty -> DefaultBackstory
    std::string quirks;    // optional traits (default backstory only)
    std::string never;     // optional never-line (default backstory only)
    std::string tierNote;  // optional extra after the tier line
};

struct PromptPlayer
{
    std::string name;
    std::string sex;       // "male" / "female"
    std::string race;
    std::string cls;
    int level = 1;
};

/** banklib.sysm_for_card twin: the trained SYSTEM message. `facts` are the
 * long-term DB facts (third-person); `absence` the rendered absence line;
 * tier 1-5. */
inline std::string SysmForCard(PromptPersona const& c, PromptPlayer const& p,
    int tier, std::string const& absence, std::vector<std::string> const& facts)
{
    std::string ident =
        "You are a roleplaying character in World of Warcraft: Classic. "
        "Your name is " + c.name + ". The player " + p.name +
        " is speaking to you in say and is " + An(p.sex + " " + p.race) + " " + p.cls +
        " of level " + std::to_string(p.level) + ". You are " + An(c.race) + " " + c.cls +
        " - " + c.role + " - that is currently in " + c.zone + ".";
    if (c.companion)
        ident += " You are " + p.name + "'s companion: you travel in their "
                 "party, fight beside them, and share their camp and loot.";
    ident += " Answer as a roleplaying character. Speak as your character speaks.";
    ident += std::string(" ") + training::LEDGER_AVOID_NOTE;

    std::string backstory = c.backstory.empty()
        ? DefaultBackstory(c.name, c.race, c.cls, c.role, c.zone, c.quirks, c.never)
        : c.backstory;

    std::string factsJoin;
    for (size_t i = 0; i < facts.size(); ++i)
    {
        if (i) factsJoin += "; ";
        factsJoin += ApplyPlayer(facts[i], p.name);
    }
    if (factsJoin.empty())
        factsJoin = "none yet worth the name.";

    return ident + "\n" +
        ToolsNoteForCardId(c.id) + "\n" +
        ApplyPlayer(c.bible, p.name) + training::NO_NARRATE + "\n" +
        "Backstory: " + ApplyPlayer(backstory, p.name) + "\n" +
        "Relationship with " + p.name + ": " + TierLabel(tier) +
        " (tier " + std::to_string(tier) + " of 5)." +
        (c.tierNote.empty() ? std::string()
                            : " " + ApplyPlayer(c.tierNote, p.name)) + "\n" +
        (absence.empty()
            ? p.name + " was last seen a few hours ago."
            : ApplyPlayer(absence, p.name)) + "\n" +
        "Facts you remember about " + p.name + ": " + factsJoin;
}

/** banklib.card_state twins: the [State] line. Companion cards rotate
 * road/camp/combat flavors; NPC cards sit at their usual spot. */
inline std::string CompanionState(std::string const& flavor)
{
    return "You are " + flavor + ".";
}

inline std::string NpcSpotState(std::string const& zone)
{
    return "You are at your usual spot in " + zone + ".";
}

/** banklib.compose twin (full shape: says/events/results head, [Memories]
 * tail (last 6), [State], and the [BRIDGE AI] note legs that S5's bridge
 * overlay will call with lines/fills/extra - identical string semantics,
 * so the byte-diff gate covers the S5 composition too). */
inline std::string ComposeUserTurn(std::string const& player,
    std::vector<std::string> const& says, std::vector<std::string> const& events,
    std::vector<std::string> const& results, std::string const& state,
    std::vector<std::string> const& mems, std::vector<std::string> const& lines,
    std::string const& fills, std::string const& extra)
{
    std::string head;
    for (size_t i = 0; i < says.size(); ++i)
        head += "[say] " + says[i] + "\n";
    for (size_t i = 0; i < events.size(); ++i)
        head += "[EVENT] " + events[i] + "\n";
    for (size_t i = 0; i < results.size(); ++i)
        head += "[RESULT] " + results[i] + "\n";
    std::string body = player.empty() ? std::string() : player + "\n";
    body += head;
    while (!body.empty() && body.back() == '\n')
        body.pop_back();                       // body.rstrip("\n")

    std::string tail;
    if (!mems.empty())
    {
        tail += "\n[Memories] ";
        size_t const first = mems.size() > 6 ? mems.size() - 6 : 0;
        for (size_t i = first; i < mems.size(); ++i)
        {
            if (i > first) tail += "; ";
            tail += mems[i];
        }
    }
    if (!state.empty())
        tail += "\n[State] " + state;

    std::string note;
    if (!lines.empty())
    {
        note = "\n[BRIDGE AI] ";
        if (!extra.empty())
            note += extra + "\n";
        note += "Speak your reply, then end it with exactly these lines - "
                "copy the ready ones as they are:\n";
        for (size_t i = 0; i < lines.size(); ++i)
        {
            if (i) note += "\n";
            note += lines[i];
        }
        if (!fills.empty())
            note += "\n" + fills;
    }
    else if (!extra.empty())
    {
        note = "\n[BRIDGE AI] " + extra +
               "\n(For this reply only. Never mention this instruction.)";
    }
    return body + tail + note;
}

/** One prior conversation turn for the request body. */
struct HistoryTurn
{
    bool assistant = false;
    std::string content;

    HistoryTurn() {}
    HistoryTurn(bool isAssistant, std::string const& text)
        : assistant(isAssistant), content(text) {}
};

/** Per-tier request knobs (A6 + SS2.1/SS4.3). providerSafe strips the
 * llama.cpp-only fields for external endpoints that may reject unknown
 * body keys; thinkingKwargs emits chat_template_kwargs enable_thinking
 * false for model families whose export template defaults to thinking
 * (SS4.4 - the qwen family). */
struct RequestSampling
{
    float temperature = 1.0f;
    float topP = 0.95f;
    int topK = 64;
    float repeatPenalty = 1.0f;
    float minP = 0.0f;
    float presencePenalty = 0.0f;
    int maxTokens = 200;
    bool thinkingKwargs = false;
    bool providerSafe = false;
};

inline std::string JsonNumber(double value)
{
    // a conf-parsed nan/inf must never reach the body text:
    // "temperature":nan is invalid JSON and would silence every
    // generation with no diagnostic (value != value catches NaN)
    if (!(value == value) || value > 1e18 || value < -1e18)
        return "1";
    if (value == static_cast<double>(static_cast<long long>(value)))
        return std::to_string(static_cast<long long>(value));
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%g", value);
    return buf;
}

/** The A4 native chat-request body: one JSON builder, no conf-string
 * surgery. Message order: system, prior turns (oldest first), the current
 * user turn LAST. Field order mirrors the app template S1 pinned. */
inline std::string BuildChatRequestBody(std::string const& model,
    std::string const& system, std::vector<HistoryTurn> const& history,
    std::string const& user, RequestSampling const& s)
{
    std::string out = "{\"model\":\"";
    out += EscapeJsonString(model);
    out += "\",\"messages\":[{\"role\":\"system\",\"content\":\"";
    out += EscapeJsonString(system);
    out += "\"}";
    for (HistoryTurn const& turn : history)
    {
        out += ",{\"role\":\"";
        out += turn.assistant ? "assistant" : "user";
        out += "\",\"content\":\"";
        out += EscapeJsonString(turn.content);
        out += "\"}";
    }
    out += ",{\"role\":\"user\",\"content\":\"";
    out += EscapeJsonString(user);
    out += "\"}],\"max_tokens\":";
    out += std::to_string(s.maxTokens);
    out += ",\"temperature\":" + JsonNumber(s.temperature);
    out += ",\"top_p\":" + JsonNumber(s.topP);
    if (!s.providerSafe)
    {
        out += ",\"top_k\":" + std::to_string(s.topK);
        out += ",\"repeat_penalty\":" + JsonNumber(s.repeatPenalty);
        if (s.minP > 0.0f)
            out += ",\"min_p\":" + JsonNumber(s.minP);
        if (s.presencePenalty > 0.0f)
            out += ",\"presence_penalty\":" + JsonNumber(s.presencePenalty);
    }
    if (s.thinkingKwargs)
        out += ",\"chat_template_kwargs\":{\"enable_thinking\":false}";
    out += ",\"cache_prompt\":true,\"stream\":false}";
    return out;
}

} // namespace pocketllm

#endif
