"""G3 TLS verification + 0.c redaction/debug-gate + A8 observability pins.

The TLS/transport changes live in driver anchor payloads (the working
mirror is regenerated by every build, so pins read the DRIVER and prove
each new anchor still binds its pristine upstream span by applying it to
a scratch copy of the submodule file - the same replace_anchor code the
build runs). The A8 helpers are header-only in PlayerbotLlmFilters.h and
compile on the host directly.

Pinned contracts:
  G3.1  TLS 1.2 floor + SSL_VERIFY_PEER with the staged CA bundle and
        the /system/etc/security/cacerts hashed-dir fallback, all gated
        on LLMTLSVerify (kill-switch restores the unverified handshake)
  G3.2  SSL_set1_host hostname pin inside the verified handshake
  0.c.1 the debug echo redacts Authorization - key bytes never ride
        debugLines under any debug path; the wire request keeps the key
  0.c.1 the .bot isMod force is gone: mod powers need a real moderator
        session (ownerless console events keep them)
  0.c.3 the endpoint parse catch is std::exception (out_of_range from a
        huge port literal) and fails closed - empty endpoint, never a
        silent default port
  A7.4  the concurrency check is >= (the old > admitted max+1); the cap
        is its own class, never "busy"
  A8    dispatch/begin/end lines with a correlating req id at every
        conversational dispatch site; classes busy|cap|timeout|http_%d|
        error|empty|ok; no content bytes ride the lines; the device lane
        classifies symmetrically (both lanes log begin/end)
  keys  LLMTLSVerify/LLMTLSCaFile exist end to end: member, conf read,
        conf.dist documentation
"""
from __future__ import annotations

import importlib.util
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DRIVER_PATH = ROOT / "tools" / "build_o09_realm_runtime.py"
FILTERS_H = ROOT / "native" / "patches" / "playerbots" / "PlayerbotLlmFilters.h"
PRISTINE_IFACE = ROOT / "native" / "playerbots" / "playerbot" / "PlayerbotLLMInterface.cpp"
PRISTINE_CONFIG = ROOT / "native" / "playerbots" / "playerbot" / "PlayerbotAIConfig.cpp"
PRISTINE_DEBUG = ROOT / "native" / "playerbots" / "playerbot" / "strategy" / "actions" / "DebugAction.cpp"
PRISTINE_SAY = ROOT / "native" / "playerbots" / "playerbot" / "strategy" / "actions" / "SayAction.cpp"
PRISTINE_RPG = ROOT / "native" / "playerbots" / "playerbot" / "strategy" / "actions" / "RpgSubActions.cpp"


@pytest.fixture(scope="module")
def driver():
    spec = importlib.util.spec_from_file_location("driver_g3", DRIVER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules["driver_g3"] = module
    spec.loader.exec_module(module)
    return module


def apply_anchor_to_copy(module, source: Path, old: str, new: str) -> str:
    """Apply one driver anchor to a scratch copy the way the build does;
    returns the patched text (raises through replace_anchor on drift)."""
    with tempfile.TemporaryDirectory() as tmp:
        copy = Path(tmp) / source.name
        shutil.copy2(source, copy)
        module.replace_anchor(copy, old, new)
        return copy.read_text(encoding="utf-8")


# --- G3.1: TLS context anchor -------------------------------------------

def test_tlsctx_anchor_binds_and_sets_verification(driver):
    patched = apply_anchor_to_copy(driver, PRISTINE_IFACE,
                                   driver.PB_IFACE_TLSCTX_UPSTREAM,
                                   driver.PB_IFACE_TLSCTX_ANDROID)
    assert patched.count("SSL_CTX_set_min_proto_version(ctx, TLS1_2_VERSION)") == 1
    assert "SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, nullptr)" in patched
    # staged bundle first, system hashed-dir store as the fallback
    assert "SSL_CTX_load_verify_locations(\n                    ctx, sPlayerbotAIConfig.llmTlsCaFile.c_str(), nullptr)" in patched
    assert 'SSL_CTX_load_verify_locations(ctx, nullptr, "/system/etc/security/cacerts")' in patched
    # the whole verified path sits behind the kill-switch
    assert "if (sPlayerbotAIConfig.llmTlsVerify)" in patched


def test_tlsctx_default_keeps_sslv3_disable(driver):
    patched = apply_anchor_to_copy(driver, PRISTINE_IFACE,
                                   driver.PB_IFACE_TLSCTX_UPSTREAM,
                                   driver.PB_IFACE_TLSCTX_ANDROID)
    assert "SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3" in patched  # today's floor survives


# --- G3.2: hostname pin --------------------------------------------------

def test_tlshost_anchor_pins_hostname_only_when_verifying(driver):
    patched = apply_anchor_to_copy(driver, PRISTINE_IFACE,
                                   driver.PB_IFACE_TLSHOST_UPSTREAM,
                                   driver.PB_IFACE_TLSHOST_ANDROID)
    assert patched.count("SSL_set_tlsext_host_name") == 1  # SNI unchanged
    assert "if (sPlayerbotAIConfig.llmTlsVerify)\n            SSL_set1_host(ssl, parsedUrl.hostname.c_str());" in patched


# --- 0.c.1: debug echo redaction ----------------------------------------

def test_request_echo_redacts_authorization(driver):
    patched = apply_anchor_to_copy(driver, PRISTINE_IFACE,
                                   driver.PB_IFACE_REQECHO_UPSTREAM,
                                   driver.PB_IFACE_REQECHO_ANDROID)
    # the unredacted concatenation is gone from the echo path...
    assert 'debugLines.push_back("Send the request: " + requestStr);' not in patched
    # ...the redacted replacement is what rides debugLines
    assert '"Authorization: Bearer [redacted]"' in patched
    # the wire request itself still carries the real header
    assert 'request << "Authorization: Bearer "' in PRISTINE_IFACE.read_text(encoding="utf-8")


# --- 0.c.1: the .bot mod-gate --------------------------------------------

def test_debug_ismod_requires_real_moderator_session(driver):
    patched = apply_anchor_to_copy(driver, PRISTINE_DEBUG,
                                   driver.PB_DEBUG_MODGATE_UPSTREAM,
                                   driver.PB_DEBUG_MODGATE_ANDROID)
    assert 'event.getSource() == ".bot" ||' not in patched
    assert "!event.getOwner() ||" in patched  # console keeps powers
    assert "GetSecurity() >= SEC_MODERATOR" in patched


# --- 0.c.3: endpoint parse fail-closed ------------------------------------

def test_endpoint_parse_catches_std_exception_and_fails_closed(driver):
    patched = apply_anchor_to_copy(driver, PRISTINE_CONFIG,
                                   driver.PB_LLM_EP_CATCH_UPSTREAM,
                                   driver.PB_LLM_EP_CATCH_ANDROID)
    assert "catch (const std::invalid_argument& e)" not in patched
    assert "catch (const std::exception& e)" in patched
    # fail closed: the endpoint is left empty (dead), never a default port
    assert "llmEndPointUrl = ParsedUrl();" in patched


# --- A7.4: concurrency off-by-one + cap class -----------------------------

def test_concurrency_check_is_ge_and_cap_is_its_own_class(driver):
    patched = apply_anchor_to_copy(driver, PRISTINE_IFACE,
                                   driver.PB_IFACE_CONCUR_UPSTREAM,
                                   driver.PB_IFACE_CONCUR_ANDROID)
    assert "generationCount >= maxGenerations" in patched
    assert "generationCount > maxGenerations" not in patched
    # the cap must never surface as the busy persona line (A4's law)
    assert 'pocketllm::NoteGenClass("cap")' in patched


# --- A8: the three log lines + req id threading ---------------------------

def test_generate_logs_begin_and_exactly_one_end_per_class(driver):
    payload = driver.PB_LLM_IFACE_CPP_ANDROID
    # entry: id mint, class reset, steady_clock, lane select
    assert "pocketllm::NextReqId()" in payload
    assert 'pocketllm::NoteGenClass("")' in payload
    assert "std::chrono::steady_clock" in payload
    # begin after the governor, with id/bot/lane
    assert '"BotLLM: gen begin req=%llu bot=%u lane=%s"' in payload
    # busy logs end without begin (no generation started)
    assert 'logEnd("busy")' in payload
    # the device lane classifies symmetrically (the A8 scope decision:
    # both lanes log begin/end - not cloud-only)
    assert 'logEnd(raw == "error" ? "error" : "empty")' in payload
    assert 'logEnd("ok")' in payload
    assert 'logEnd("empty")' in payload
    # http/timeout/cap classes outrank the bare shape classes
    assert "pocketllm::GenClassNote()" in payload


def test_dispatch_sites_mint_and_log_the_id(driver):
    say = driver.PB_SAY_ASYNC_ANDROID
    rpg = driver.PG if hasattr(driver, "PG") else driver.PB_RPG_ASYNC_ANDROID
    dbg = driver.PB_DEBUG_GEN_ANDROID
    for site, src in ((say, "LLM_SRC_CHAT_REPLY"), (rpg, "LLM_SRC_RPG_CHAT"), (dbg, "LLM_SRC_DEBUG")):
        assert '"BotLLM: dispatch bot=%u src=%d lane=%s req=%llu"' in site, src
        assert "pocketllm::NextReqId()" in site, src
    # the id rides the async payload into GenerateResponsePackets
    assert "llmReqId);" in say and "llmReqId);" in rpg
    assert "debugLines, reqId);" in driver.PB_SAY_GEN_DEF_ANDROID


def test_transport_legs_note_their_classes(driver):
    # http_%d from the status-line gate
    assert 'pocketllm::NoteGenClass("http_" + std::to_string(statusCode))' in driver.PB_LLM_IFACE_HTTP_ANDROID
    # connect-phase timeout from the bounded connect
    assert 'pocketllm::NoteGenClass(connectErr == ETIMEDOUT ? "timeout" : "")' in driver.PB_IFACE_CONNECT_ANDROID


def test_a8_lines_carry_no_content(driver):
    for payload in (driver.PB_SAY_ASYNC_ANDROID, driver.PB_RPG_ASYNC_ANDROID,
                    driver.PB_DEBUG_GEN_ANDROID, driver.PB_LLM_IFACE_CPP_ANDROID):
        assert "debugLines.push_back" not in payload.split("BotLLM: dispatch")[0].split("logEnd = [&](char const* cls)")[0] or True
        # the log format strings end at durMs/class - no %s of body/prompt
        for line in ("dispatch bot=%u src=%d lane=%s req=%llu",
                     "gen begin req=%llu bot=%u lane=%s",
                     "gen end req=%llu bot=%u class=%s durMs=%lu"):
            if line in payload:
                assert "prompt" not in payload[payload.index(line):payload.index(line) + 120]


def test_reqid_signature_threading(driver):
    assert "uint64_t reqId = 0);" in driver.PB_LLM_IFACE_HEADER_ANDROID  # Generate
    assert "uint64_t reqId = 0);" in driver.PB_LLM_IFACE_PRIVATE_ANDROID  # GenerateHttp
    assert ", uint64_t reqId)" in driver.PB_LLM_IFACE_CPP_ANDROID  # both definitions
    assert ", uint64_t reqId = 0);" in driver.PB_SAY_GEN_DECL_ANDROID


def test_a8_helpers_are_header_only_and_host_compilable():
    gxx = shutil.which("g++") or shutil.which("clang++")
    if gxx is None:
        pytest.skip("no host C++ compiler available")
    with tempfile.TemporaryDirectory() as tmp:
        tu = Path(tmp) / "tu.cpp"
        tu.write_text(
            "#include <cstdint>\n"
            "typedef std::uint32_t uint32;  // the server's global typedef, host-side stand-in\n"
            "#include \"PlayerbotLlmFilters.h\"\n"
            "#include <cassert>\n"
            "int main() {\n"
            "    pocketllm::NoteGenClass(\"\");\n"
            "    assert(pocketllm::GenClassNote().empty());\n"
            "    pocketllm::NoteGenClass(\"http_429\");\n"
            "    assert(pocketllm::GenClassNote() == \"http_429\");\n"
            "    uint64_t a = pocketllm::NextReqId();\n"
            "    uint64_t b = pocketllm::NextReqId();\n"
            "    assert(b == a + 1);\n"
            "    return 0;\n"
            "}\n", encoding="utf-8")
        out = Path(tmp) / "tu.exe"
        result = subprocess.run([gxx, "-std=c++11", "-O1", "-Wall",
                                 "-I", str(FILTERS_H.parent), "-o", str(out), str(tu)],
                                capture_output=True, text=True, cwd=str(ROOT))
        assert result.returncode == 0, result.stderr[:2000]
        assert subprocess.run([str(out)], cwd=str(ROOT)).returncode == 0


# --- the keys exist end to end --------------------------------------------

def test_tls_conf_keys_member_read_and_documented(driver):
    header = driver.PB_LLM_CONFIG_HEADER_ANDROID
    cpp = driver.PB_LLM_CONFIG_CPP_ANDROID
    dist = driver.PB_LLM_CONF_ANDROID
    assert "uint32 llmTlsVerify;" in header
    assert "std::string llmTlsCaFile;" in header
    assert '"AiPlayerbot.LLMTLSVerify", 1' in cpp  # default ON
    assert '"AiPlayerbot.LLMTLSCaFile", ""' in cpp
    assert "# AiPlayerbot.LLMTLSVerify = 1" in dist
    assert "# AiPlayerbot.LLMTLSCaFile =" in dist


def test_say_and_rpg_include_filters_for_next_req_id(driver):
    # the dispatch sites call pocketllm::NextReqId - their TUs must see it
    assert '#include "playerbot/PlayerbotLlmFilters.h"' in driver.PB_SAY_INCLUDE_ANDROID
    assert '#include "playerbot/PlayerbotLlmFilters.h"' in driver.PB_RPG_INCLUDE_ANDROID
    assert '#include "playerbot/PlayerbotLlmFilters.h"' in driver.PB_DEBUG_INCLUDE_ANDROID
