"""The A4/A5 trained prompt-format battery (S4 gate).

Compiles the SHIPPED headers (PlayerbotLlmPrompt.h + PlayerbotLlmJson.h)
on the host with -std=c++11 and runs two legs against the committed
vectors (tests/llm_prompt_vectors.json, generated by
tools/llm_lab/gen_prompt_vectors.py from banklib - the training source of
truth):

* bytediff: THE stage gate - every row's system prompt and user turn must
  match the banklib rendering with at most whitespace differences, and
  >= 20 rows must be present. (The corpus also pins the training text
  itself: any drift in the verbatim constants fails here.)
* bodydump: the native request-body builder round-trips through the
  shipped JSON client, keeps system/history/current-turn order, lands the
  per-tier sampling and SS4.4 thinking-kwargs fields, strips
  llama.cpp-only fields in providerSafe mode, and stays compatible with
  S2's retry splice.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PATCHES = ROOT / "native" / "patches" / "playerbots"
HEADER = PATCHES / "PlayerbotLlmPrompt.h"
HARNESS = ROOT / "tools" / "test_llm_prompt_format.cpp"
VECTORS = ROOT / "tests" / "llm_prompt_vectors.json"


@pytest.fixture(scope="session")
def prompt_binary(tmp_path_factory):
    gxx = shutil.which("g++") or shutil.which("clang++")
    if gxx is None:
        pytest.skip("no host C++ compiler available")
    if not HEADER.is_file() or not HARNESS.is_file() or not VECTORS.is_file():
        pytest.skip("prompt-format core or vectors not staged")
    tmp = tmp_path_factory.mktemp("promptfmt")
    exe = tmp / "prompt_format_test.exe"
    build = subprocess.run(
        [gxx, "-std=c++11", "-O2", "-Wall", "-I", str(PATCHES),
         "-o", str(exe), str(HARNESS)],
        capture_output=True, text=True, timeout=300)
    if build.returncode != 0:
        pytest.fail(f"host compile failed:\n{build.stderr[:4000]}")
    return exe


def test_byte_diff_gate_20_rows_whitespace_only(prompt_binary):
    result = subprocess.run(
        [str(prompt_binary), "bytediff", str(VECTORS)],
        capture_output=True, text=True, timeout=300)
    assert result.returncode == 0, result.stdout + result.stderr[:2000]
    lines = [l for l in result.stdout.splitlines() if l.startswith("{")]
    assert lines, "bytediff produced no JSON"
    data = json.loads(lines[-1])
    # the gate: >= 20 rows, zero mismatches beyond whitespace
    assert data["rows"] >= 20
    assert data["mismatches"] == 0, f"{data['mismatches']} non-whitespace mismatches"
    # the corpus must exercise every tier and both note legs
    assert data["whitespace_only"] + data["sysm_byte_exact"] == data["rows"]
    assert "prompt-format byte-diff gate passed" in result.stdout


def test_vectors_cover_tiers_and_note_legs():
    rows = json.loads(VECTORS.read_text(encoding="utf-8"))
    tiers = {r["tier"] for r in rows}
    assert tiers == {1, 2, 3, 4, 5}, f"tier coverage incomplete: {sorted(tiers)}"
    # at least one [BRIDGE AI] lines-note row, one extra-note row, one
    # [Memories] row, one says/events/results head row (the compose surface
    # S5's bridge overlay will reuse)
    assert any(r["user"]["lines"] for r in rows), "no lines-note row"
    assert any(r["user"]["extra"] for r in rows), "no extra-note row"
    assert any(r["user"]["mems"] for r in rows), "no memories row"
    assert any(r["user"]["says"] or r["user"]["events"] or r["user"]["results"]
               for r in rows), "no says/events/results head row"
    # the memories tail cap (last 6) is exercised by an 8-mem row
    assert any(len(r["user"]["mems"]) > 6 for r in rows), "no >6 mems row"


def test_request_body_invariants_leg(prompt_binary):
    result = subprocess.run(
        [str(prompt_binary), "bodydump", str(VECTORS)],
        capture_output=True, text=True, timeout=300)
    assert result.returncode == 0, result.stdout + result.stderr[:2000]
    assert "request-body invariants passed" in result.stdout


def test_training_text_constants_are_the_generated_block():
    text = HEADER.read_text(encoding="utf-8")
    # the verbatim block must stay machine-emitted (regenerate with
    # tools/llm_lab/emit_prompt_constants.py - it SPLICES the block into
    # the existing header in place; the header's logic outside the markers
    # is hand-maintained)
    assert "do not hand-edit between the markers" in text
    for anchor in ("TOOLS_NOTE_A", "BIBLE_GRUMPH", "LEDGER_AVOID_NOTE",
                   "NO_NARRATE", "SysmForCard", "ComposeUserTurn",
                   "BuildChatRequestBody", "ToolsNoteForCardId"):
        assert anchor in text, f"contract anchor missing: {anchor}"


def test_emitted_wording_is_fresh_against_banklib():
    """The S11 wording locks both ways: this leg regenerates the verbatim
    constants AND the beat-cargo frames in memory and diffs them against
    the headers, so a banklib edit that did not re-run the emitter (or a
    hand edit between the markers) fails loud. Skips with reason on a
    machine without the G: authoring tree, matching the suite's standing
    hermeticity treatment of banklib-dependent legs."""
    if not (ROOT / "tools" / "llm_lab" / "emit_prompt_constants.py").is_file():
        pytest.skip("emitter not staged")
    if not Path(r"G:\NPU LLM\scripts\finetune").is_dir():
        pytest.skip("authoring tree (G:\\NPU LLM) not present on this machine")
    emitter = ROOT / "tools" / "llm_lab" / "emit_prompt_constants.py"
    r = subprocess.run([sys.executable, str(emitter), "--check"],
                       capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, \
        f"emitter drift:\n{r.stdout}\n{r.stderr}"
