package com.pocketrealm.llm

import android.content.Context
import android.content.Intent
import java.io.File

/** Compute placement for the llama-server process.
 *
 *  - [AUTO]: Hexagon NPU hybrid when [HexagonProbe] reports READY, CPU otherwise.
 *  - [CPU]: plain llama.cpp on the pinned CPU cores (KleidiAI/dotprod build).
 *  - [NPU]: HTP hybrid — `--device HTP0`, prefill on the Hexagon (core-invariant
 *    ~430-540 tok/s), decode scales with the pinned CPU cores. Falls back to
 *    CPU automatically after repeated load deaths (see LlmRuntimeService).
 */
enum class ComputeMode { AUTO, CPU, NPU }

/**
 * Public API for embedding the LLM runtime. All values are the defaults we
 * validated on the QCS8550 (Retroid Pocket 6); tune via [Builder].
 *
 * Resource rules proven on-device (findings log 2026-08-19 .. 2026-08-28):
 *  - threads confined to mid cores 3-5, nice 10: game client coexists cleanly;
 *  - decode cores are the whole story in NPU mode (prefill is HTP-bound and
 *    core-invariant): 3×mid balanced, 2×mid low-draw, 1×mid lowest power;
 *  - MTP speculative decoding is a measured net loss on pinned cores — keep off;
 *  - start the runtime BEFORE the game container claims its memory.
 */
data class LlmRuntimeConfig(
    val modelFile: String,                 // absolute path to the .gguf inside app storage
    val port: Int = 8080,
    val bindLoopbackOnly: Boolean = true,  // true = cmangos runs inside pocketrealm; false = LAN clients (PC server)
    val apiKey: String = "",               // required when bindLoopbackOnly = false
    val threads: Int = 3,
    val cpuMaskHex: Long = 0x38L,          // cores 3-5 (mids). 0 = no affinity.
    val nice: Int = 10,
    // 8192 since rev-3 (2026-08-31): the measured worst-case trained request
    // is ~2.2k tokens (largest session row + template + era-bias + a full
    // asset lore card) and the P50/P51 banks grow the GENERATION side
    // (max_tokens up to 300) plus headroom for future history growth. KV
    // RAM at 8192 is re-checked on the G4 device matrix; --cache-type q8_0
    // is the fallback lever if pressure shows.
    val contextSize: Int = 8192,
    val computeMode: ComputeMode = ComputeMode.AUTO,
    val npuLayers: Int = 99,               // -ngl for the HTP offload; 99 = all layers
    val useMtp: Boolean = false,           // requires an MTP-enabled GGUF; forced off in NPU mode
    val mtpDraftMax: Int = 3,
    val extraArgs: List<String> = emptyList(), // e.g. ["--jinja", "--flash-attn"]
    // §4.4 (LLM-INTEGRATION): absolute staged path of the non-thinking chat
    // template override. When non-null AND the post-healthy warm-up probe
    // sees the model's own template burn the budget on a thinking preamble
    // (reasoning_content / empty content), the service restarts the child
    // once with --chat-template <this file's CONTENT> - the vendored
    // 6d05498 binary predates the --chat-template-file flag (string-extract
    // verified; the desktop b10520 has both). Null = no override armed; the
    // probe still runs (it also pays the measured first-request penalty).
    val chatTemplateFile: String? = null,
) : java.io.Serializable {
    companion object {
        // Pinned BEFORE the chatTemplateFile field landed: sticky restarts
        // deliver the persisted pre-field config as an Intent extra, and an
        // autogenerated UID would silently reject it (the :llm process would
        // stop instead of resuming a realm whose bots still POST to us).
        private const val serialVersionUID = 1L
    }

    class Builder(var modelFile: String) {
        var port = 8080
        var bindLoopbackOnly = true
        var apiKey = ""
        var threads = 3
        var cpuMaskHex = 0x38L
        var nice = 10
        var contextSize = 8192
        var computeMode = ComputeMode.AUTO
        var npuLayers = 99
        var useMtp = false
        var mtpDraftMax = 3
        var extraArgs: List<String> = emptyList()
        var chatTemplateFile: String? = null

        fun build() = LlmRuntimeConfig(
            modelFile, port, bindLoopbackOnly, apiKey, threads, cpuMaskHex,
            nice, contextSize, computeMode, npuLayers, useMtp, mtpDraftMax, extraArgs,
            chatTemplateFile,
        )
    }
}

object LlmRuntime {

    internal const val PREFS = "llm_runtime"
    internal const val KEY_NPU_BLOCKED = "npuBlocked"
    internal const val KEY_LAST_CONFIG = "lastConfig"

    /**
     * The persisted NPU crash-block, readable without a running service
     * (the block survives process death; live broadcasts only flow once the
     * service is up). UIs combine this with [HexagonProbe.probe] so they
     * never show "NPU ready" while the next start is guaranteed CPU.
     *
     * Deliberately NOT getSharedPreferences: Android caches the parsed file
     * per process, and the writer lives in the separate :llm process — a
     * cached read could serve a stale `blocked` (or miss a reset) forever.
     * Parsing the small XML on the caller's IO thread reads the fresh file
     * every time (framework writes are atomic renames).
     */
    fun isNpuBlocked(context: Context): Boolean = try {
        val file = File(File(context.applicationInfo.dataDir, "shared_prefs"), "$PREFS.xml")
        if (file.isFile) {
            Regex("<boolean name=\"$KEY_NPU_BLOCKED\" value=\"(true|false)\"")
                .find(file.readText())?.groupValues?.get(1) == "true"
        } else {
            false
        }
    } catch (_: Exception) {
        false
    }

    /** Start (or restart with new config) the runtime service. Fire-and-forget. */
    fun start(context: Context, config: LlmRuntimeConfig) {
        val i = intent(context).putExtra(LlmRuntimeService.EXTRA_CONFIG, config)
        context.startForegroundService(i)
    }

    fun stop(context: Context) {
        context.startService(intent(context).setAction(LlmRuntimeService.ACTION_STOP))
    }

    /** Clear a persisted NPU-blocked flag (after the user inspected a failure). */
    fun resetNpuBlock(context: Context) {
        context.startService(intent(context).setAction(LlmRuntimeService.ACTION_NPU_RESET))
    }

    /** Endpoint to configure in aiplayerbot.conf: AiPlayerbot.LLMApiEndpoint. */
    fun endpoint(config: LlmRuntimeConfig): String {
        val host = if (config.bindLoopbackOnly) "127.0.0.1" else "0.0.0.0"
        return "http://$host:${config.port}/v1/chat/completions"
    }

    private fun intent(context: Context) =
        Intent(context, LlmRuntimeService::class.java)
}
