#!/usr/bin/env python3
"""Generate the Kotlin Vulkan package identities from the reviewed JSON catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "schemas" / "vulkan-driver-catalog.json"
OUTPUT = (
    ROOT / "android" / "app" / "src" / "main" / "java" / "com" /
    "pocketrealm" / "client" / "GeneratedVulkanDriverCatalog.kt"
)
EXPECTED_IDS = {"system-vulkan-vortek-2.1", "turnip-26.1.0"}
LIBRARY_ROLES = {"guest-vulkan-bridge-library", "guest-vulkan-icd-library"}
MANIFEST_ROLE = "guest-vulkan-icd-manifest"


def kotlin_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_catalog() -> dict[str, object]:
    raw = CATALOG.read_bytes()
    catalog = json.loads(raw)
    if catalog.get("schema") != 2:
        raise RuntimeError("unsupported Vulkan driver catalog schema")
    if catalog.get("selection_policy") != "exact-request-fail-closed":
        raise RuntimeError("Vulkan driver selection must fail closed")
    drivers = catalog.get("drivers")
    if not isinstance(drivers, list):
        raise RuntimeError("Vulkan driver catalog has no driver list")
    ids = {driver.get("id") for driver in drivers if isinstance(driver, dict)}
    if len(drivers) != len(EXPECTED_IDS) or ids != EXPECTED_IDS:
        raise RuntimeError(f"Vulkan driver catalog is not the closed set: {ids}")
    if catalog.get("default") not in ids:
        raise RuntimeError("Vulkan driver default is not present")

    for driver in drivers:
        driver_id = driver["id"]
        if driver.get("kind") not in {"system-vortek", "turnip"}:
            raise RuntimeError(f"unsupported Vulkan driver kind: {driver.get('kind')}")
        display = driver.get("display")
        if not isinstance(display, dict) or not all(
            isinstance(display.get(field), str) and display[field].strip()
            for field in ("label", "summary", "qualification")
        ):
            raise RuntimeError(f"Vulkan driver display metadata is incomplete: {driver_id}")
        files = driver.get("files")
        if not isinstance(files, list) or len(files) != 2:
            raise RuntimeError(f"Vulkan driver must have one library and one manifest: {driver_id}")
        roles = {entry.get("role") for entry in files if isinstance(entry, dict)}
        if len(roles & LIBRARY_ROLES) != 1 or MANIFEST_ROLE not in roles:
            raise RuntimeError(f"Vulkan driver file roles are invalid: {driver_id}")
        for entry in files:
            asset = entry.get("asset")
            digest = entry.get("sha256")
            if not isinstance(asset, str) or PurePosixPath(asset).parent != PurePosixPath(
                f"arm-translated/vulkan-drivers/{driver_id}"
            ):
                raise RuntimeError(f"Vulkan driver asset escapes its package: {asset}")
            if not isinstance(entry.get("size"), int) or entry["size"] <= 0:
                raise RuntimeError(f"Vulkan driver asset size is invalid: {asset}")
            if not isinstance(digest, str) or len(digest) != 64 or any(
                char not in "0123456789abcdef" for char in digest
            ):
                raise RuntimeError(f"Vulkan driver asset digest is invalid: {asset}")
    return catalog


def render(catalog: dict[str, object]) -> bytes:
    source_digest = hashlib.sha256(CATALOG.read_bytes()).hexdigest()
    lines = [
        "// Generated by tools/generate_vulkan_driver_catalog.py.",
        "// Edit schemas/vulkan-driver-catalog.json, then regenerate; do not edit this file.",
        "package com.pocketrealm.client",
        "",
        "internal object GeneratedVulkanDriverCatalog {",
        f"    const val SCHEMA: Int = {catalog['schema']}",
        f"    const val DEFAULT_ID: String = {kotlin_string(catalog['default'])}",
        "    const val SELECTION_POLICY: String = "
        f"{kotlin_string(catalog['selection_policy'])}",
        f"    const val SOURCE_CATALOG_SHA256: String = {kotlin_string(source_digest)}",
        "",
        "    val packages: List<VulkanDriverPackage> = listOf(",
    ]
    for driver in catalog["drivers"]:
        files = driver["files"]
        library = next(entry for entry in files if entry["role"] in LIBRARY_ROLES)
        manifest = next(entry for entry in files if entry["role"] == MANIFEST_ROLE)
        display = driver["display"]
        kind = "SYSTEM" if driver["kind"] == "system-vortek" else "TURNIP"
        lines.extend([
            "        VulkanDriverPackage(",
            f"            id = {kotlin_string(driver['id'])},",
            f"            label = {kotlin_string(display['label'])},",
            f"            version = {kotlin_string(driver['version'])},",
            f"            kind = VulkanDriverKind.{kind},",
            f"            summary = {kotlin_string(display['summary'])},",
            f"            qualification = {kotlin_string(display['qualification'])},",
            f"            libraryAsset = {kotlin_string(library['asset'])},",
            f"            libraryName = {kotlin_string(PurePosixPath(library['asset']).name)},",
            f"            librarySha256 = {kotlin_string(library['sha256'])},",
            f"            icdAsset = {kotlin_string(manifest['asset'])},",
            f"            icdFileName = {kotlin_string(PurePosixPath(manifest['asset']).name)},",
            f"            icdSha256 = {kotlin_string(manifest['sha256'])},",
            "        ),",
        ])
    lines.extend(["    )", "}", ""])
    return "\n".join(lines).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in Kotlin source is not exactly regenerated",
    )
    args = parser.parse_args()
    rendered = render(load_catalog())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_bytes() != rendered:
            raise RuntimeError(
                "GeneratedVulkanDriverCatalog.kt is stale; run "
                "python tools/generate_vulkan_driver_catalog.py"
            )
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
