package com.pocketrealm.llm

import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.ObjectInputStream
import java.io.ObjectOutputStream
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * §4.4 (S9): the runtime config is persisted (Base64 through the service's
 * prefs) and re-delivered on a sticky restart — a sticky restart after the
 * :llm process died must resume the realm's runtime, so the serialized form
 * is a compatibility contract. The serialVersionUID is pinned BEFORE the
 * chatTemplateFile field landed (an autogenerated UID would silently reject
 * every pre-field persisted config and stop the runtime instead of
 * resuming it).
 */
class LlmRuntimeConfigTest {

    @Test
    fun serialVersionUidIsPinnedForStickyRestarts() {
        val field = LlmRuntimeConfig::class.java.getDeclaredField("serialVersionUID")
        field.isAccessible = true
        assertEquals(1L, field.get(null))
    }

    @Test
    fun roundTripsThroughJavaSerializationWithTheTemplateOverride() {
        val config = LlmRuntimeConfig.Builder("/data/models/gemma.gguf").apply {
            chatTemplateFile = "/data/data/app/files/llm/chat_template_nonthinking.jinja"
            computeMode = ComputeMode.NPU
        }.build()
        val bytes = ByteArrayOutputStream().use { out ->
            ObjectOutputStream(out).writeObject(config)
            out.toByteArray()
        }
        val restored = ObjectInputStream(ByteArrayInputStream(bytes)).readObject()
        assertTrue(restored is LlmRuntimeConfig)
        restored as LlmRuntimeConfig
        assertEquals(config.chatTemplateFile, restored.chatTemplateFile)
        assertEquals(config.modelFile, restored.modelFile)
        assertEquals(config.computeMode, restored.computeMode)
        assertEquals(config.extraArgs, restored.extraArgs)
    }

    @Test
    fun chatTemplateFileDefaultsToNullFailingOpen() {
        val config = LlmRuntimeConfig.Builder("/data/models/qwen.gguf").build()
        assertNull(config.chatTemplateFile)
    }
}
