import java.security.MessageDigest

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.pocketrealm"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.pocketrealm"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        // G0–G3 development ABI. arm64-v8a is added at G5 once the same
        // contracts pass on x86_64.
        ndk {
            abiFilters += "x86_64"
        }
    }

    // PKG-01 (report §8.4) requires executing an APK-packaged PIE launcher from
    // nativeLibraryDir. That only happens reliably when AGP *extracts* native
    // libs to disk with the executable bit, i.e. useLegacyPackaging=true. The
    // "pkgExperiment" build type is that experiment variant; the standard
    // "debug"/"release" types keep useLegacyPackaging=false (production: .so
    // stored uncompressed/page-aligned in the APK, may have no fs exec path).
    // PKG-02/PKG-06 run against the production packaging variant.
    buildTypes {
        getByName("debug") {
            // production packaging model
        }
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
        create("pkgExperiment") {
            initWith(getByName("debug"))
            // Experiment variant: force extraction so the launcher has an
            // executable filesystem path in nativeLibraryDir.
            isJniDebuggable = true
        }
        create("clientRuntime") {
            initWith(getByName("debug"))
            // O06's qualified x86DirectWine product lane. Unlike the O05
            // control variants, Wine must execute APK-managed ELFs from
            // nativeLibraryDir; extraction is selected below per-variant.
            isJniDebuggable = true
        }
        create("databaseRuntime") {
            initWith(getByName("debug"))
            // O08's MariaDB/glibc ELFs execute from nativeLibraryDir, using the
            // same qualified immutable-code packaging model as O06.
            isJniDebuggable = true
        }
        create("realmRuntime") {
            initWith(getByName("debug"))
            // O09 integration lane: O08's executable MariaDB provider plus
            // Android-native realmd/world libraries in separate processes.
            isJniDebuggable = true
        }
    }

    // Per-variant jniLibs packaging model. O05 documents the observed behavior
    // of each lane; the production variants (debug/release) intentionally do
    // NOT require an executable fs path. The pkgExperiment variant overrides
    // this to true via androidComponents below.
    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    sourceSets {
        getByName("main") {
            // Deterministic staged native closure (see stageNativeLibs task).
            // Never references ../../../native — staged inside the module.
            jniLibs.srcDir("build/staged-jniLibs")
            // O06: Wine-owned PE modules as APK assets (the hash-verified
            // guest-code cache source). Generated by tools/stage_wine_runtime.py
            // into native/.build-x86_64/wine-staging/assets/.
            assets.srcDir("../..//native/.build-x86_64/wine-staging/assets")
            // O06 S-3: Winlator X-server (vendored at ca3d735; trimmed/stubbed).
            // See docs/patches/wine-provider-provenance.md for the trim list.
            java.srcDir("../../runtime/xserver-winlator")
        }
        getByName("databaseRuntime") {
            // Generated, deterministic provider support data + gzip migration
            // inputs. Executable code remains in nativeLibraryDir.
            assets.srcDir("../../native/.build-x86_64/mariadb-staging/assets")
        }
        getByName("realmRuntime") {
            assets.srcDir("../../native/.build-x86_64/mariadb-staging/assets")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
        // O05: IPkgIsolation AIDL crosses the :pkg process boundary.
        aidl = true
    }

    testOptions {
        // Instrumented tests run against the real supervisor/service on-device;
        // animations are disabled for deterministic lifecycle observation.
        animationsDisabled = true
        // Host JVM unit tests touch android.util.Log via AppLog; return defaults
        // rather than throwing "not mocked" so model/unit tests stay pure-JVM.
        unitTests {
            isReturnDefaultValues = true
        }
    }
}

// Resolve the NDK via the same ndk-link junction build_native.py creates, then
// fall back to a discovered ndk/<version> dir. Used only to locate
// libc++_shared.so for the staged closure.
val sdkRoot = providers.environmentVariable("ANDROID_SDK_ROOT")
    .orElse(providers.environmentVariable("ANDROID_HOME")).orElse("")
val ndkLinkPath = sdkRoot.map { "$it/ndk-link" }
val ndkVersionsPath = sdkRoot.map { "$it/ndk" }
val ndkRootProvider = provider {
    val link = File(ndkLinkPath.get())
    if (link.isDirectory) return@provider link
    val versionsDir = File(ndkVersionsPath.get())
    if (versionsDir.isDirectory) {
        versionsDir.listFiles()?.filter { it.isDirectory }
            ?.maxByOrNull { it.name }?.let { return@provider it }
    }
    error("NDK not found under ANDROID_SDK_ROOT/ndk[-link]. Run scripts/build_native.py first.")
}

// Stages the complete native dependency closure into build/staged-jniLibs/x86_64.
// APK assembly depends on this task. Packages only app-supplied libs (the realm
// facade, the packaging JNI shim, the PIE launcher, the O06 Wine spike helper,
// and the Wine/glibc ELFs); platform libs (libc/libm/libdl/liblog) are supplied
// by Android, never staged (except the glibc closure, which is a SEPARATE
// Linux/glibc namespace — those are Wine's deps, not Android's).
val stageNativeLibs by tasks.registering(Sync::class) {
    group = "pocket realm"
    description = "Stage the native .so closure for APK packaging (x86_64)."

    val repoRoot = layout.projectDirectory.dir("../..").asFile
    val rtBuild = File(repoRoot, "native/.build-x86_64/pocket-runtime-build")
    val pkgBuild = File(repoRoot, "native/.build-x86_64/packaging-build")
    val wineSpikeBuild = File(repoRoot, "native/.build-x86_64/wine-spike-build")
    val xserverBuild = File(repoRoot, "native/.build-x86_64/xserver-winlator-build")
    val wineStaging = File(repoRoot, "native/.build-x86_64/wine-staging/jniLibs")
    val prootStage = File(repoRoot, "native/.build-x86_64/proot-stage")
    val mariadbStage = File(repoRoot, "native/.build-x86_64/mariadb-staging/jniLibs/x86_64")
    val realmStage = File(repoRoot, "native/.build-o09-x86_64/realm-staging/jniLibs/x86_64")
    val extractorStage = File(repoRoot, "native/.build-o11-x86_64/extractor-staging/jniLibs/x86_64")
    val stagedLib = layout.buildDirectory.dir("staged-jniLibs/x86_64")

    // Require the native build to have run (O03/O04 + O05 packaging + O06 spike).
    doFirst {
        val required = listOf(
            File(rtBuild, "libpocketrealm.so"),
            File(pkgBuild, "libpocketpkgtest.so"),
            File(pkgBuild, "libpocket_pkg_launcher.so"),
            File(wineSpikeBuild, "libwine_spike.so"),
            File(wineSpikeBuild, "libwine_trampoline.so"),
            File(wineSpikeBuild, "libwine_android_shim.so"),
            File(xserverBuild, "libwinlator.so"),
        )
        val missing = required.filter { !it.isFile }
        check(missing.isEmpty()) {
            "Missing staged native artifacts (run scripts/build_native.py --abi x86_64 all, " +
                "tools/build_packaging.py, tools/build_wine_spike.py, " +
                "tools/build_xserver_winlator.py): " +
                missing.joinToString { it.name }
        }
        check(wineStaging.isDirectory) {
            "Wine staging not found at $wineStaging. Run: python tools/stage_wine_runtime.py"
        }
        check(prootStage.isDirectory) {
            "proot staging not found at $prootStage. Run: python tools/build_proot.py --abi x86_64"
        }
        val serverLibraries = listOf(
            File(realmStage, "libpocket_realmd_runtime.so"),
            File(realmStage, "libpocket_world_runtime.so"),
        )
        check(serverLibraries.all { it.isFile }) {
            "O09 native realm staging is incomplete. Run: python tools/build_o09_realm_runtime.py"
        }
        val extractors = listOf("libpocket_ad.so", "libpocket_vmap_extractor.so",
            "libpocket_vmap_assembler.so", "libpocket_movemapgen.so")
            .map { File(extractorStage, it) }
        check(extractors.all { it.isFile }) {
            "O11 extractor staging is incomplete. Run: python tools/build_o11_extractors.py"
        }
    }

    into(stagedLib)
    // Real realm facade (O04) — large APK-native .so, loaded by SONAME in PKG-02/06.
    from(File(rtBuild, "libpocketrealm.so"))
    // PKG JNI shim + dlopen/crash helper.
    from(File(pkgBuild, "libpocketpkgtest.so"))
    // PKG-01 PIE launcher (a .so-named executable; extracted under the
    // experiment variant).
    from(File(pkgBuild, "libpocket_pkg_launcher.so"))
    // O06: Wine spike JNI helper (symlink-tree builder + loader launcher +
    // /proc maps probe + PE cache + S-5 SIGSYS diagnostic + trampoline launcher).
    // Runs in the Android/Bionic namespace.
    from(File(wineSpikeBuild, "libwine_spike.so"))
    // O06 S-5(a): APK-packaged Bionic trampoline PIE (re-execve's the glibc
    // loader). Named lib*.so so AGP extracts it with the +x bit; it is a PIE
    // executable, not a shared library.
    from(File(wineSpikeBuild, "libwine_trampoline.so"))
    // O06 direct-glibc path: glibc LD_PRELOAD path/syscall shim, built in the
    // pinned Linux CGCT container by tools/build_wine_glibc_shim.py.
    from(File(wineSpikeBuild, "libwine_android_shim.so"))
    // O06 S-5(b): proot fallback (termux/proot@a89b3732, Bionic PIE) + libtalloc.
    // Required because Android's untrusted_app seccomp filter kills the glibc
    // loader on its access(2) syscall (PROVEN via ptrace diagnostic). proot
    // intercepts syscalls via ptrace and translates access->faccessat.
    from(File(prootStage, "libproot.so"))
    from(File(prootStage, "libtalloc.so"))
    // O06 S-5(b): proot's in-tracee helper loader, staged APK-managed as
    // libproot_loader.so. PROOT_LOADER=<nativeLibraryDir>/libproot_loader.so
    // makes proot use this immutable +x copy directly instead of extracting
    // one to writable PROOT_TMP_DIR (which the app domain forbids: noexec).
    from(File(prootStage, "libproot_loader.so"))
    from(File(prootStage, "libproot_loader32.so"))
    // O06 S-3: Winlator X-server native transport (vendored source-matched from
    // ca3d735). libwinlator.so provides the epoll accept loop, buffered X11
    // input/output with SCM_RIGHTS fd-passing, and Drawable BGRA ops. JNI
    // methods match the vendored Java classes' package paths exactly
    // (com.winlator.xconnector.* + com.winlator.xserver.Drawable), so it is a
    // drop-in for System.loadLibrary("winlator").
    from(File(xserverBuild, "libwinlator.so"))
    // O07: source-matched Winlator GLX/OpenGL bridge. WineD3D needs this
    // extension to render the imported 1.12.1 client; GDI-only O06 did not.
    from(File(xserverBuild, "libgladiorenderer.so"))
    // libc++_shared.so — the realm facade links ANDROID_STL=c++_shared, so its
    // runtime closure needs the shared C++ runtime. Sourced from the NDK, never
    // from a platform path. Platform libs (libc/libm/libdl/liblog) are excluded.
    from(provider {
        val ndk = ndkRootProvider.get()
        File(ndk, "toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/x86_64-linux-android/libc++_shared.so")
    })
    // O06: the Wine + glibc ELF closure (53 files: glibc loader + libs, gcc-libs,
    // X11/font libs, Wine binaries + 36 unix .so modules). These run in the
    // SEPARATE Linux/glibc namespace (execve'd via the APK-managed loader).
    // Generated by tools/stage_wine_runtime.py.
    from(wineStaging)
    // Direct-glibc fallback: Wine's installed second-stage loader resolves
    // ntdll.so beside /proc/self/exe before WINEDLLPATH is initialized. Keep a
    // source-named APK-managed alias alongside the collision-safe staged name.
    from(File(wineStaging, "libwine_unix_ntdll.so")) {
        rename { "ntdll.so" }
    }
    // O08: pinned MariaDB executables + their glibc DT_NEEDED closure. The
    // stage script assigns collision-safe lib*.so APK names and records every
    // source pathname/hash in BUILD_PROVENANCE.json.
    from(mariadbStage)
    // O09: Android/Bionic, no-bot CMaNGOS components. Each library is loaded
    // only inside its dedicated :realm or :world process.
    from(realmStage)
    // O11: finite, fixed-purpose Android/Bionic PIE extractors. These are
    // invoked only by the isolated import worker after managed-copy publication.
    from(extractorStage)
}

val validateDatabaseRuntime by tasks.registering {
    group = "pocket realm"
    description = "Require the generated O08 MariaDB provider and migration assets."
    val repoRoot = layout.projectDirectory.dir("../..").asFile
    doLast {
        val stage = File(repoRoot, "native/.build-x86_64/mariadb-staging")
        val required = listOf(
            File(stage, "jniLibs/x86_64/libpocket_mariadbd.so"),
            File(stage, "jniLibs/x86_64/libpocket_mariadb_client.so"),
            File(stage, "assets/database/provider/bootstrap.sql"),
            File(stage, "assets/database/migrations/manifest.json"),
            File(stage, "BUILD_PROVENANCE.json"),
        )
        val missing = required.filterNot { it.isFile }
        check(missing.isEmpty()) {
            "O08 MariaDB staging incomplete. Run tools/stage_mariadb_runtime.py and " +
                "tools/stage_database_migrations.py. Missing: ${missing.joinToString { it.name }}"
        }
    }
}

val validateRealmRuntime by tasks.registering {
    group = "pocket realm"
    description = "Require realm ELF artifacts to match both the lockfile and generated provenance."
    val repoRoot = layout.projectDirectory.dir("../..").asFile
    doLast {
        fun sha256Hex(file: File): String {
            val digest = MessageDigest.getInstance("SHA-256")
            file.inputStream().use { input ->
                val buffer = ByteArray(1 shl 16)
                while (true) {
                    val count = input.read(buffer)
                    if (count < 0) break
                    digest.update(buffer, 0, count)
                }
            }
            return digest.digest().joinToString("") { "%02x".format(it) }
        }
        val lockPath = "native/.build-o09-x86_64/realm-staging/jniLibs/x86_64/"
        val lockText = File(repoRoot, "schemas/realm-runtime-lockfile.json").readText()
        val provenance = File(repoRoot, "native/.build-o09-x86_64/realm-staging/BUILD_PROVENANCE.json")
        check(provenance.isFile) { "O09 BUILD_PROVENANCE.json is missing; rebuild realm runtime" }
        val provenanceText = provenance.readText()
        val files = listOf("libpocket_realmd_runtime.so", "libpocket_world_runtime.so")
        for (name in files) {
            val relative = "$lockPath$name"
            val recordPattern = Regex(
                "(?s)\\{\\s*\"path\"\\s*:\\s*\"" +
                    Regex.escape(relative) +
                    "\"\\s*,\\s*\"size\"\\s*:\\s*(\\d+)\\s*,\\s*\"sha256\"\\s*:\\s*\"([0-9a-fA-F]{64})\""
            )
            val lock = recordPattern.find(lockText)
                ?: error("realm lockfile has no record for $relative")
            val provenanceRecord = recordPattern.find(provenanceText)
                ?: error("realm provenance has no record for $relative")
            check(lock.groupValues[1] == provenanceRecord.groupValues[1] &&
                lock.groupValues[2].equals(provenanceRecord.groupValues[2], ignoreCase = true)) {
                "realm provenance disagrees with lockfile for $name"
            }
            val artifact = File(repoRoot, relative)
            check(artifact.isFile) { "missing staged realm artifact: $artifact" }
            check(artifact.length() == lock.groupValues[1].toLong()) {
                "realm artifact size disagrees with lockfile: $name"
            }
            check(sha256Hex(artifact).equals(lock.groupValues[2], ignoreCase = true)) {
                "realm artifact SHA-256 disagrees with lockfile: $name"
            }
        }
    }
}

// Make every APK-producing variant depend on staging the native closure, and
// force the pkgExperiment variant to extract .so to disk with +x so the PKG-01
// launcher has an executable filesystem path in nativeLibraryDir.
androidComponents {
    onVariants { variant ->
        val cap = variant.name.replaceFirstChar { c -> c.uppercase() }
        tasks.matching { it.name == "merge${cap}JniLibFolders" }
            .configureEach { dependsOn(stageNativeLibs) }
        tasks.matching { it.name.startsWith("assemble") && it.name.endsWith(cap) }
            .configureEach { dependsOn(stageNativeLibs) }
        if (variant.name == "pkgExperiment" || variant.name == "clientRuntime" ||
            variant.name == "databaseRuntime" || variant.name == "realmRuntime") {
            variant.packaging.jniLibs.useLegacyPackaging.set(true)
        }
        if (variant.name == "databaseRuntime") {
            tasks.matching { it.name == "merge${cap}JniLibFolders" ||
                it.name == "merge${cap}Assets" || it.name == "assemble${cap}" }
                .configureEach { dependsOn(validateDatabaseRuntime) }
        }
        if (variant.name == "realmRuntime") {
            tasks.matching { it.name == "merge${cap}JniLibFolders" ||
                it.name == "merge${cap}Assets" || it.name == "assemble${cap}" }
                .configureEach { dependsOn(validateDatabaseRuntime, validateRealmRuntime) }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.service)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.kotlinx.coroutines.android)
    debugImplementation(libs.androidx.compose.ui.tooling)

    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.kotlinx.coroutines.test)

    // Host JVM unit tests (O04: RealmNative shim graceful-degradation test).
    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation("org.json:json:20240303")
}
